/**
 * VocRehab banks pack 3 — seeded item banks for 5 games.
 *
 * Games: resume-rescue, inbox-sprint, schedule-juggle, paycheck-plan, energy-budget.
 * Each bank holds >= 20 items; draws are deterministic per seed via ./vocrehab-seed.
 *
 * Local fallback note: if "./vocrehab-seed" is unavailable, replace the import
 * with a local xmur3 + mulberry32 + Fisher-Yates fallback (same algorithm family
 * as ./vocrehab-seed: xmur3 string hash feeding mulberry32, Fisher-Yates over a copy).
 *
 * Pure module: zero DOM, zero I/O, safe for client + server.
 */

import { mulberry32, shuffle, xmur3 } from "./vocrehab-seed";

export type VocrehabPack3Game =
  | "resume-rescue"
  | "inbox-sprint"
  | "schedule-juggle"
  | "paycheck-plan"
  | "energy-budget";

export type VocrehabPack3Difficulty = "beginner" | "standard" | "brisk";

export interface VocrehabBank3Item {
  id: string;
  gameId: VocrehabPack3Game;
  prompt: string;
  choices?: readonly string[];
  answer?: string;
  difficulty: VocrehabPack3Difficulty;
  criteria: string;
}

export interface VocrehabPack3Draw {
  seed: string;
  items: VocrehabBank3Item[];
  criteria: string[];
}

const RR = "resume-rescue" as const;
const IS = "inbox-sprint" as const;
const SJ = "schedule-juggle" as const;
const PP = "paycheck-plan" as const;
const EB = "energy-budget" as const;

const resumeRescueBank: readonly VocrehabBank3Item[] = [
  { id: "rr-01", gameId: RR, prompt: "Resume line: 'Responsible for stuff at old job.'", choices: ["Led restocking for a 6-person grocery shift", "Responsible for stuff at old job", "Did many various things daily"], answer: "Led restocking for a 6-person grocery shift", difficulty: "beginner", criteria: "replace vague duties with a specific action + scope" },
  { id: "rr-02", gameId: RR, prompt: "Resume line: 'Hard worker, fast learner, team player.'", choices: ["Cashier, 1 yr: 98% scan accuracy, trained 3 new hires", "Hard worker, fast learner, team player", "Great attitude and hustle"], answer: "Cashier, 1 yr: 98% scan accuracy, trained 3 new hires", difficulty: "beginner", criteria: "swap adjectives for a role + tenure + measurable result" },
  { id: "rr-03", gameId: RR, prompt: "Resume line: 'References available upon request.'", choices: ["References: Maria Lopez, shift lead, (555) 014-2200", "References available upon request", "Ask me for references later"], answer: "References: Maria Lopez, shift lead, (555) 014-2200", difficulty: "beginner", criteria: "name a real reference with title and contact" },
  { id: "rr-04", gameId: RR, prompt: "Resume line: 'Helped customers.'", choices: ["Resolved ~40 customer requests per shift at returns desk", "Helped customers", "Customer service stuff"], answer: "Resolved ~40 customer requests per shift at returns desk", difficulty: "standard", criteria: "quantify volume and name the station" },
  { id: "rr-05", gameId: RR, prompt: "Resume line: 'Worked 2019-2021, then nothing.' (2-yr gap, no note)", choices: ["2021-2023: full-time caregiver for parent; returned to work 2023", "Leave the gap unexplained", "Stretch 2021 job dates to cover the gap"], answer: "2021-2023: full-time caregiver for parent; returned to work 2023", difficulty: "standard", criteria: "address gaps honestly with a one-line note" },
  { id: "rr-06", gameId: RR, prompt: "Resume line: 'Proficient in Microsft Office.'", choices: ["Proficient in Microsoft Office (Word, Excel)", "Proficient in Microsft Office", "Good at computer"], answer: "Proficient in Microsoft Office (Word, Excel)", difficulty: "beginner", criteria: "fix spelling; name the actual tools" },
  { id: "rr-07", gameId: RR, prompt: "Resume line: 'Salary: $18/hr minimum!!!'", choices: ["Remove salary demand from the resume; discuss pay at interview", "Salary: $18/hr minimum!!!", "Salary negotiable!!! call me"], answer: "Remove salary demand from the resume; discuss pay at interview", difficulty: "beginner", criteria: "keep pay demands off the resume" },
  { id: "rr-08", gameId: RR, prompt: "Resume line: whole resume in ALL CAPS, 3 pages for one job.", choices: ["One page, normal case, most recent job first", "Keep all caps so it stands out", "Add a fourth page with hobbies"], answer: "One page, normal case, most recent job first", difficulty: "beginner", criteria: "one page, readable formatting, reverse-chronological" },
  { id: "rr-09", gameId: RR, prompt: "Resume line: 'Contact: xX_gamer_Xx99@email.com'", choices: ["Contact: jordan.lee@email.com, (555) 010-4471", "Contact: xX_gamer_Xx99@email.com", "No contact info; they can find me"], answer: "Contact: jordan.lee@email.com, (555) 010-4471", difficulty: "beginner", criteria: "professional email + phone in the header" },
  { id: "rr-10", gameId: RR, prompt: "Resume line: 'Fired from last job for arguing.'", choices: ["Omit the firing note; prepare a calm 2-sentence explanation for interviews", "Fired from last job for arguing", "Badmouth the old boss in detail"], answer: "Omit the firing note; prepare a calm 2-sentence explanation for interviews", difficulty: "standard", criteria: "resume shows history, not grievances; save explanations for interviews" },
  { id: "rr-11", gameId: RR, prompt: "Resume line: 'Skills: everything, quick learner.'", choices: ["Skills: POS systems, food safety cert, forklift license", "Skills: everything, quick learner", "Skills: TBD"], answer: "Skills: POS systems, food safety cert, forklift license", difficulty: "standard", criteria: "list concrete, checkable skills" },
  { id: "rr-12", gameId: RR, prompt: "Resume line: job titles with no dates or employers.", choices: ["Add employer + city + start/end month-year per role", "Titles alone are fine", "Remove all titles"], answer: "Add employer + city + start/end month-year per role", difficulty: "standard", criteria: "every role needs employer, location, and dates" },
  { id: "rr-13", gameId: RR, prompt: "Resume line: 'Increased sales a lot.'", choices: ["Grew accessory sales 15% in Q3 via register prompts", "Increased sales a lot", "Best salesperson ever"], answer: "Grew accessory sales 15% in Q3 via register prompts", difficulty: "brisk", criteria: "pair every claim with a number and a method" },
  { id: "rr-14", gameId: RR, prompt: "Resume line: photo, age, and marital status in the header.", choices: ["Header holds name, phone, email, city only", "Keep photo, age, marital status", "Add social security number too"], answer: "Header holds name, phone, email, city only", difficulty: "standard", criteria: "no photo or personal demographics on a US resume" },
  { id: "rr-15", gameId: RR, prompt: "Resume line: 'Objective: any job that pays.'", choices: ["Target line: 'Seeking stock associate role; evening availability'", "Objective: any job that pays", "No target line at all, ever"], answer: "Target line: 'Seeking stock associate role; evening availability'", difficulty: "standard", criteria: "name the role you want + one availability fact" },
  { id: "rr-16", gameId: RR, prompt: "Resume line: 5 paragraphs describing one dishwashing job.", choices: ["3 bullets: load 200+ racks/shift, chem checks, closing duties", "Keep all 5 paragraphs", "Delete the job entirely"], answer: "3 bullets: load 200+ racks/shift, chem checks, closing duties", difficulty: "brisk", criteria: "3-4 bullets per role, strongest result first" },
  { id: "rr-17", gameId: RR, prompt: "Resume line: 'Reason for leaving: boss was unfair.'", choices: ["Drop the reason-for-leaving column entirely", "Reason for leaving: boss was unfair", "Reason for leaving: hated it"], answer: "Drop the reason-for-leaving column entirely", difficulty: "beginner", criteria: "never list reasons for leaving on the resume" },
  { id: "rr-18", gameId: RR, prompt: "Resume line: inconsistent verbs — 'Running register, stocked shelves, will clean.'", choices: ["Ran register, stocked shelves, cleaned dining area", "Running register, stocked shelves, will clean", "Register running, shelves stocked-ish"], answer: "Ran register, stocked shelves, cleaned dining area", difficulty: "brisk", criteria: "parallel past-tense verbs across bullets" },
  { id: "rr-19", gameId: RR, prompt: "Resume line: 'Certification: CPR (expired 2019).'", choices: ["Either renew CPR or list only current certs", "List the expired cert with no date", "Invent a 2025 renewal date"], answer: "Either renew CPR or list only current certs", difficulty: "brisk", criteria: "only current credentials; never invent dates" },
  { id: "rr-20", gameId: RR, prompt: "Resume line: two different fonts, emojis, and a joke footer.", choices: ["One clean font, no emojis, plain footer with page count", "Keep the emojis for personality", "Add more fonts for flair"], answer: "One clean font, no emojis, plain footer with page count", difficulty: "beginner", criteria: "consistent readable formatting; let content carry personality" },
  { id: "rr-21", gameId: RR, prompt: "Resume line: 'Volunteer work doesn't count, left it off.'", choices: ["Add it: 'Food bank volunteer, 8 hrs/mo: packed 150 boxes'", "Leave volunteer work off forever", "List it as paid employment"], answer: "Add it: 'Food bank volunteer, 8 hrs/mo: packed 150 boxes'", difficulty: "standard", criteria: "count real volunteer work with hours + output" },
  { id: "rr-22", gameId: RR, prompt: "Resume line: 'Can start ASAP!!! Call anytime day or night!!!'", choices: ["Availability: weekdays after 3pm, weekends open", "Can start ASAP!!! Call anytime day or night!!!", "No availability info at all"], answer: "Availability: weekdays after 3pm, weekends open", difficulty: "beginner", criteria: "state concrete availability windows" },
];

const inboxSprintBank: readonly VocrehabBank3Item[] = [
  { id: "is-01", gameId: IS, prompt: "From: manager@workplace.com | Subject: 'Shift swap approved for Friday' | Snippet: 'As requested, your Friday swap with Dee is approved. See the posted schedule.'", answer: "verdict:legit;action:reply", difficulty: "beginner", criteria: "known sender + expected topic + no link pressure = reply" },
  { id: "is-02", gameId: IS, prompt: "From: payr0ll-update@secure-pay-services.net | Subject: 'URGENT: verify direct deposit in 24h' | Snippet: 'Click here to confirm banking or pay is paused.'", answer: "verdict:phish;action:flag", difficulty: "beginner", criteria: "lookalike domain + urgency + credential link = flag" },
  { id: "is-03", gameId: IS, prompt: "From: hr@company.com | Subject: 'Benefits enrollment opens Monday' | Snippet: 'Review options on the intranet benefits page when ready.'", answer: "verdict:legit;action:file", difficulty: "beginner", criteria: "internal sender + no attachment demand = file for later" },
  { id: "is-04", gameId: IS, prompt: "From: ceo@company-secure.com | Subject: 'Buy gift cards ASAP, in meeting' | Snippet: 'Need 5 cards, send codes now, reimburse later.'", answer: "verdict:phish;action:flag", difficulty: "beginner", criteria: "authority impersonation + gift cards + secrecy = flag" },
  { id: "is-05", gameId: IS, prompt: "From: scheduler@clinic.org | Subject: 'Appointment reminder: Tue 10:30am' | Snippet: 'Reply YES to confirm or call the front desk to reschedule.'", answer: "verdict:legit;action:reply", difficulty: "beginner", criteria: "expected reminder + phone option, no link = reply" },
  { id: "is-06", gameId: IS, prompt: "From: support@micros0ft-helpdesk.com | Subject: 'Virus detected, call now' | Snippet: 'Your device is locked. Call this number with your password.'", answer: "verdict:phish;action:flag", difficulty: "standard", criteria: "brand typo + fear + password request = flag" },
  { id: "is-07", gameId: IS, prompt: "From: coworker.dee@company.com | Subject: 'Cover my Saturday?' | Snippet: 'Can you cover 2-6pm Saturday? I can take your Sunday.'", answer: "verdict:legit;action:reply", difficulty: "beginner", criteria: "known coworker + concrete swap offer = reply" },
  { id: "is-08", gameId: IS, prompt: "From: no-reply@bank.com | Subject: 'Statement ready' | Snippet: 'Your statement is ready. Sign in via the bank app (do not reply).'", answer: "verdict:legit;action:file", difficulty: "standard", criteria: "no-reply notice + app (not link) + no action = file" },
  { id: "is-09", gameId: IS, prompt: "From: prizes@luckywinner-claim.biz | Subject: 'You WON a $500 gift card!' | Snippet: 'Pay $2 shipping to claim. Enter card details.'", answer: "verdict:phish;action:flag", difficulty: "beginner", criteria: "prize + upfront fee + card harvest = flag" },
  { id: "is-10", gameId: IS, prompt: "From: landlord@propertymgmt.com | Subject: 'Lease renewal draft attached (PDF)' | Snippet: 'Review the attached draft before Friday; no login needed.'", answer: "verdict:legit;action:schedule", difficulty: "standard", criteria: "expected document + clear next step = schedule review time" },
  { id: "is-11", gameId: IS, prompt: "From: it-help@company.com | Subject: 'Password expires in 14 days' | Snippet: 'Change it anytime in Settings > Password. Never share it.'", answer: "verdict:legit;action:file", difficulty: "standard", criteria: "advance notice + self-serve path + no link = file" },
  { id: "is-12", gameId: IS, prompt: "From: it-helpdesk@company-support.io | Subject: 'Password expired — reset via this link' | Snippet: 'External form: enter old + new password to reactivate.'", answer: "verdict:phish;action:flag", difficulty: "standard", criteria: "external domain + credential form link = flag" },
  { id: "is-13", gameId: IS, prompt: "From: transit@authority.gov | Subject: 'Reduced-fare card renewal' | Snippet: 'Renew at any station kiosk or the official site you already use.'", answer: "verdict:legit;action:schedule", difficulty: "standard", criteria: "public service + kiosk option, no credential ask = schedule" },
  { id: "is-14", gameId: IS, prompt: "From: docsign@e-sign-delivery.com | Subject: 'Sign: updated W-4' | Snippet: 'Your employer sent a W-4. Sign via link; SSN required upfront.'", answer: "verdict:phish;action:flag", difficulty: "brisk", criteria: "unexpected tax doc + SSN upfront + odd domain = flag" },
  { id: "is-15", gameId: IS, prompt: "From: coach@trainingcenter.org | Subject: 'Resume workshop Thursday 6pm' | Snippet: 'Bring a printed resume. Reply to save a seat.'", answer: "verdict:legit;action:reply", difficulty: "beginner", criteria: "known program + in-person details = reply" },
  { id: "is-16", gameId: IS, prompt: "From: deliveries@track-package.info | Subject: 'Package held: pay redelivery' | Snippet: 'You missed delivery (no order placed). Pay via crypto link.'", answer: "verdict:phish;action:flag", difficulty: "standard", criteria: "no order + crypto payment link = flag" },
  { id: "is-17", gameId: IS, prompt: "From: payroll@company.com | Subject: 'Pay stub available' | Snippet: 'View in the payroll portal. Contact payroll with questions.'", answer: "verdict:legit;action:file", difficulty: "beginner", criteria: "routine notice + portal (not link) = file" },
  { id: "is-18", gameId: IS, prompt: "From: vendor-invoices@supplies-co.com | Subject: 'Invoice #4412 due (you never ordered)' | Snippet: 'Wire payment to new account; attachment is a .zip.'", answer: "verdict:phish;action:flag", difficulty: "brisk", criteria: "unknown invoice + wire + zip attachment = flag" },
  { id: "is-19", gameId: IS, prompt: "From: library@citylib.org | Subject: 'Hold ready: interview prep book' | Snippet: 'Pick up within 7 days at the front desk.'", answer: "verdict:legit;action:schedule", difficulty: "beginner", criteria: "expected hold + pickup instruction = schedule" },
  { id: "is-20", gameId: IS, prompt: "From: careers@job-board.com | Subject: 'Interview invite: warehouse associate' | Snippet: 'You applied last week. Reply with two time slots; no fees.'", answer: "verdict:legit;action:reply", difficulty: "standard", criteria: "matches an application + no fee = reply" },
  { id: "is-21", gameId: IS, prompt: "From: security-alerts@account-verify.net | Subject: 'Unusual sign-in — confirm identity' | Snippet: 'Enter full SSN + bank login to unlock. Link expires in 1 hour.'", answer: "verdict:phish;action:flag", difficulty: "brisk", criteria: "SSN + bank login + countdown = flag" },
  { id: "is-22", gameId: IS, prompt: "From: mentor@nonprofit.org | Subject: 'Mock interview notes attached' | Snippet: 'Notes from Tuesday attached. Next session same time next week?'", answer: "verdict:legit;action:reply", difficulty: "standard", criteria: "ongoing thread + expected attachment = reply" },
];

const scheduleJuggleBank: readonly VocrehabBank3Item[] = [
  { id: "sj-01", gameId: SJ, prompt: "Constraint card: Bus pass works after 9am only. Shift starts 8am across town.", choices: ["Request 9:30am start or a closer stop", "Miss the first hour silently", "Quit the bus route"], answer: "Request 9:30am start or a closer stop", difficulty: "beginner", criteria: "match start time to real transit limits" },
  { id: "sj-02", gameId: SJ, prompt: "Constraint card: Child pickup 3pm daily. Offered shift ends 4pm.", choices: ["Ask for 2pm end or a pickup backup plan first", "Accept and figure out pickup later", "Skip pickup twice a week"], answer: "Ask for 2pm end or a pickup backup plan first", difficulty: "beginner", criteria: "lock dependent care before accepting hours" },
  { id: "sj-03", gameId: SJ, prompt: "Constraint card: Two part-time jobs overlap Saturday 12-4pm.", choices: ["Keep higher-pay job; offer Sundays to the other", "Work both at once", "No-show to both"], answer: "Keep higher-pay job; offer Sundays to the other", difficulty: "standard", criteria: "resolve double-booking with one keep + one counteroffer" },
  { id: "sj-04", gameId: SJ, prompt: "Constraint card: Night class Tue/Thu 6-8pm. Boss adds Thu overtime.", choices: ["Trade Thursday OT for Wednesday OT", "Drop the class without telling anyone", "Sleep through the class"], answer: "Trade Thursday OT for Wednesday OT", difficulty: "standard", criteria: "protect fixed classes; trade equivalent hours" },
  { id: "sj-05", gameId: SJ, prompt: "Constraint card: Medication must be taken with dinner at 6pm; shift has no break.", choices: ["Request a 10-min 6pm break as a medical need", "Skip doses on workdays", "Take it at midnight instead"], answer: "Request a 10-min 6pm break as a medical need", difficulty: "standard", criteria: "surface health needs as a specific break request" },
  { id: "sj-06", gameId: SJ, prompt: "Constraint card: Interview 10am, current shift 9am-1pm.", choices: ["Swap the morning shift or take unpaid hour off", "Call out sick with no notice", "Do the interview on the sales floor"], answer: "Swap the morning shift or take unpaid hour off", difficulty: "beginner", criteria: "use swaps/time-off, never stealth interviews" },
  { id: "sj-07", gameId: SJ, prompt: "Constraint card: Three deadlines land Friday: rent form, cert quiz, shift bid.", choices: ["Do rent form Wed, quiz Thu, bid Fri morning", "All three Friday night", "Skip the shift bid"], answer: "Do rent form Wed, quiz Thu, bid Fri morning", difficulty: "standard", criteria: "spread deadlines across days, earliest impact first" },
  { id: "sj-08", gameId: SJ, prompt: "Constraint card: Roommate needs quiet after 10pm; you study 10pm-12am.", choices: ["Move study to 7-9am library slot", "Study aloud at midnight", "Stop studying"], answer: "Move study to 7-9am library slot", difficulty: "beginner", criteria: "relocate the flexible block, keep the fixed one" },
  { id: "sj-09", gameId: SJ, prompt: "Constraint card: Overtime offered Sunday; you promised family dinner.", choices: ["Decline once, offer next Sunday instead", "Accept and ghost dinner", "Accept and bring work to dinner"], answer: "Decline once, offer next Sunday instead", difficulty: "beginner", criteria: "decline with a specific alternate offer" },
  { id: "sj-10", gameId: SJ, prompt: "Constraint card: Doctor appointment vs. mandatory training, same hour.", choices: ["Ask training lead for the makeup session time", "Skip the doctor visit", "Skip training silently"], answer: "Ask training lead for the makeup session time", difficulty: "standard", criteria: "health first; book the official makeup path" },
  { id: "sj-11", gameId: SJ, prompt: "Constraint card: 90-min commute each way; 6am opens all week.", choices: ["Bid 4 ten-hour shifts to cut one commute day", "Drive sleepy all week", "Arrive late daily"], answer: "Bid 4 ten-hour shifts to cut one commute day", difficulty: "brisk", criteria: "compress shifts to cut commute load" },
  { id: "sj-12", gameId: SJ, prompt: "Constraint card: Phone dies by noon; schedule lives in an app.", choices: ["Print the weekly schedule + carry a charger", "Guess your shifts", "Borrow strangers' phones daily"], answer: "Print the weekly schedule + carry a charger", difficulty: "beginner", criteria: "keep a paper backup of digital schedules" },
  { id: "sj-13", gameId: SJ, prompt: "Constraint card: Therapy every Wed 4pm; new rota puts you on Wed 2-6pm.", choices: ["Request Wednesdays off for a recurring appointment", "Cancel therapy for the season", "Leave mid-shift weekly"], answer: "Request Wednesdays off for a recurring appointment", difficulty: "standard", criteria: "declare recurring appointments at scheduling time" },
  { id: "sj-14", gameId: SJ, prompt: "Constraint card: Two exams Monday; closing shifts Sat + Sun night.", choices: ["Trade Sunday close for Sunday morning", "Pull two all-nighters", "Skip both exams"], answer: "Trade Sunday close for Sunday morning", difficulty: "brisk", criteria: "trade the night before a fixed morning load" },
  { id: "sj-15", gameId: SJ, prompt: "Constraint card: Carpool leaves 7:15am sharp; you run late daily.", choices: ["Set a 6:30am alarm + bag packed by the door", "Text 'wait!' every morning", "Find a new carpool weekly"], answer: "Set a 6:30am alarm + bag packed by the door", difficulty: "beginner", criteria: "fix the departure routine, not the riders" },
  { id: "sj-16", gameId: SJ, prompt: "Constraint card: Holiday blackout vs. planned family trip.", choices: ["Ask about blackout dates before booking travel", "Book anyway and call out", "Cancel the job by text"], answer: "Ask about blackout dates before booking travel", difficulty: "standard", criteria: "confirm blackout windows before committing money" },
  { id: "sj-17", gameId: SJ, prompt: "Constraint card: Training runs over; bus leaves in 10 min.", choices: ["Tell the trainer the bus time; ask for notes on the tail", "Sneak out mid-sentence", "Miss the bus and pay for a ride"], answer: "Tell the trainer the bus time; ask for notes on the tail", difficulty: "standard", criteria: "name the hard stop early + capture what you miss" },
  { id: "sj-18", gameId: SJ, prompt: "Constraint card: Back-to-back doubles Fri-Sun every week; grades slipping.", choices: ["Cap at one double; keep Sunday for study", "Keep all doubles, drop classes", "Energy drinks as a plan"], answer: "Cap at one double; keep Sunday for study", difficulty: "brisk", criteria: "cap peak load; ring-fence recovery/study time" },
  { id: "sj-19", gameId: SJ, prompt: "Constraint card: On-call Saturday with no end time given.", choices: ["Ask: window, pay rule, and how late notice runs", "Wait by the phone all weekend", "Ignore the call"], answer: "Ask: window, pay rule, and how late notice runs", difficulty: "brisk", criteria: "convert on-call fog into window + pay + notice terms" },
  { id: "sj-20", gameId: SJ, prompt: "Constraint card: New baby at home; offered 5am bakery shifts.", choices: ["Take 5am shifts; sleep block 8pm-4am agreed with partner", "Take nights too for double pay", "Decline all work for a year"], answer: "Take 5am shifts; sleep block 8pm-4am agreed with partner", difficulty: "brisk", criteria: "align shift with a negotiated sleep block" },
  { id: "sj-21", gameId: SJ, prompt: "Constraint card: Volunteer shift and paid shift overlap monthly.", choices: ["Paid shift wins; move volunteering to off-weeks", "Skip paid shift quietly", "Do neither"], answer: "Paid shift wins; move volunteering to off-weeks", difficulty: "beginner", criteria: "paid commitments outrank flexible ones" },
  { id: "sj-22", gameId: SJ, prompt: "Constraint card: Winter storm delays buses 30+ min all week.", choices: ["Leave 45 min early; text the lead each morning", "Arrive late and say nothing", "Call out all week"], answer: "Leave 45 min early; text the lead each morning", difficulty: "standard", criteria: "pad travel + over-communicate during disruptions" },
];

const paycheckPlanBank: readonly VocrehabBank3Item[] = [
  { id: "pp-01", gameId: PP, prompt: "Budget scenario: $640 biweekly. Rent $500/mo, bus $60/mo, food $200/mo. What first?", choices: ["Pay rent, then food, then bus — in that order", "New headphones first", "Split evenly across wants"], answer: "Pay rent, then food, then bus — in that order", difficulty: "beginner", criteria: "fund shelter, food, transport before wants" },
  { id: "pp-02", gameId: PP, prompt: "Budget scenario: first paycheck $310. $90 phone bill due, $40 owed to a friend.", choices: ["Pay phone, repay friend, save the rest", "Spend it all celebrating", "Ignore both bills"], answer: "Pay phone, repay friend, save the rest", difficulty: "beginner", criteria: "clear due bills + debts before discretionary spend" },
  { id: "pp-03", gameId: PP, prompt: "Budget scenario: $200/month left after bills. No savings yet.", choices: ["Auto-move $50 to savings each payday", "Keep it all in checking for snacks", "Lend it out"], answer: "Auto-move $50 to savings each payday", difficulty: "beginner", criteria: "pay yourself a fixed amount first" },
  { id: "pp-04", gameId: PP, prompt: "Budget scenario: hours cut 20%. Subscriptions total $47/mo.", choices: ["Cancel unused subs; keep one", "Keep all subs, skip groceries", "Borrow to cover subs"], answer: "Cancel unused subs; keep one", difficulty: "standard", criteria: "cut recurring wants when income drops" },
  { id: "pp-05", gameId: PP, prompt: "Budget scenario: $800 tax refund arrives with $600 card debt at 24% APR.", choices: ["Wipe the card debt, save $200", "Buy a TV with it all", "Split across five gadgets"], answer: "Wipe the card debt, save $200", difficulty: "standard", criteria: "kill high-interest debt before spending windfalls" },
  { id: "pp-06", gameId: PP, prompt: "Budget scenario: payday loan offers $300 now for $380 in two weeks.", choices: ["Decline; ask employer about pay advance or aid fund", "Take it, roll it over", "Take two of them"], answer: "Decline; ask employer about pay advance or aid fund", difficulty: "standard", criteria: "avoid triple-digit-APR loans; seek advances/aid" },
  { id: "pp-07", gameId: PP, prompt: "Budget scenario: groceries $240/mo but $90 goes to spoiled food.", choices: ["Plan 3 meals, shop with a list, freeze extras", "Shop hungry with no list", "Order takeout nightly"], answer: "Plan 3 meals, shop with a list, freeze extras", difficulty: "standard", criteria: "meal plan + list + freeze to cut waste" },
  { id: "pp-08", gameId: PP, prompt: "Budget scenario: two cards: $400 at 24%, $900 at 12%. Extra $150/mo.", choices: ["Throw all $150 at the 24% card", "Split evenly", "Pay minimums, spend the extra"], answer: "Throw all $150 at the 24% card", difficulty: "brisk", criteria: "avalanche: extra payments hit the highest rate" },
  { id: "pp-09", gameId: PP, prompt: "Budget scenario: car repair $450. Emergency fund $120.", choices: ["Pay $120, payment-plan the rest, pause wants", "Put it on the 24% card silently", "Skip rent to pay it all"], answer: "Pay $120, payment-plan the rest, pause wants", difficulty: "standard", criteria: "split shocks: cash + plan + freeze wants" },
  { id: "pp-10", gameId: PP, prompt: "Budget scenario: new job pays weekly vs old biweekly; rent due monthly.", choices: ["Hold one week's pay as a rent buffer", "Spend each check fully", "Assume weekly means extra money"], answer: "Hold one week's pay as a rent buffer", difficulty: "standard", criteria: "buffer lumpy pay cycles against monthly bills" },
  { id: "pp-11", gameId: PP, prompt: "Budget scenario: side gig adds $180/mo but costs $60 in gas.", choices: ["Count $120 net; track mileage weekly", "Count $180 pure profit", "Ignore the gas cost"], answer: "Count $120 net; track mileage weekly", difficulty: "brisk", criteria: "budget net income after work costs" },
  { id: "pp-12", gameId: PP, prompt: "Budget scenario: landlord offers $40 off for autopay on the 1st.", choices: ["Enable autopay with a 3-day balance alert", "Keep paying late with fees", "Pay cash with no receipt"], answer: "Enable autopay with a 3-day balance alert", difficulty: "beginner", criteria: "capture autopay discounts with overdraft guardrails" },
  { id: "pp-13", gameId: PP, prompt: "Budget scenario: $60 sneakers vs $60 steel-toe boots required for work.", choices: ["Buy the required boots; sneakers wait", "Buy sneakers, borrow boots", "Buy neither, hope"], answer: "Buy the required boots; sneakers wait", difficulty: "beginner", criteria: "work-required gear beats wants" },
  { id: "pp-14", gameId: PP, prompt: "Budget scenario: friend asks for a $100 loan; you have $140 to payday.", choices: ["Decline or gift $20 you can lose", "Lend the $100", "Co-sign their loan"], answer: "Decline or gift $20 you can lose", difficulty: "standard", criteria: "never lend bill money; gift only what you can lose" },
  { id: "pp-15", gameId: PP, prompt: "Budget scenario: overtime month nets +$300. Usual spend absorbs it all.", choices: ["Split: $150 debt, $100 savings, $50 fun", "Lifestyle-spend all $300", "Hide it in checking"], answer: "Split: $150 debt, $100 savings, $50 fun", difficulty: "brisk", criteria: "pre-assign windfalls: debt/savings/fun" },
  { id: "pp-16", gameId: PP, prompt: "Budget scenario: bank charges $12/mo fee; free account exists.", choices: ["Switch to the free account", "Pay the fee forever", "Close all accounts"], answer: "Switch to the free account", difficulty: "beginner", criteria: "eliminate avoidable fees first" },
  { id: "pp-17", gameId: PP, prompt: "Budget scenario: holiday gifts $200 vs $180 electric bill.", choices: ["Pay electric; set a $30 gift cap", "Gifts first, power later", "Skip both"], answer: "Pay electric; set a $30 gift cap", difficulty: "standard", criteria: "utilities before gifts; cap the rest" },
  { id: "pp-18", gameId: PP, prompt: "Budget scenario: credit limit raised $500 to $2000; you carry a balance.", choices: ["Keep spending flat; raise payments", "Spend to the new limit", "Open another card"], answer: "Keep spending flat; raise payments", difficulty: "brisk", criteria: "treat limit raises as risk, not income" },
  { id: "pp-19", gameId: PP, prompt: "Budget scenario: $35 overdraft fee hit twice; payday in 6 days.", choices: ["Pause card, go cash-only, call bank for one waiver", "Keep swiping the card", "Take a payday loan"], answer: "Pause card, go cash-only, call bank for one waiver", difficulty: "standard", criteria: "stop the bleed: cash-only + ask for a waiver" },
  { id: "pp-20", gameId: PP, prompt: "Budget scenario: goal: $1000 emergency fund in 10 months.", choices: ["$25/week auto-transfer; track monthly", "$1000 next week somehow", "No plan, hope"], answer: "$25/week auto-transfer; track monthly", difficulty: "beginner", criteria: "turn goals into weekly auto-transfers" },
  { id: "pp-21", gameId: PP, prompt: "Budget scenario: rent rises $60; income flat. Eating out $120/mo.", choices: ["Cap eating out at $40; cover the rent gap", "Miss rent partially", "Borrow monthly"], answer: "Cap eating out at $40; cover the rent gap", difficulty: "standard", criteria: "offset fixed-cost rises with variable cuts" },
  { id: "pp-22", gameId: PP, prompt: "Budget scenario: 3rd-party check-cashing takes 3% each week.", choices: ["Open a free checking account for direct deposit", "Keep paying 3% weekly", "Cash under the mattress"], answer: "Open a free checking account for direct deposit", difficulty: "beginner", criteria: "direct deposit beats weekly cashing fees" },
];

const energyBudgetBank: readonly VocrehabBank3Item[] = [
  { id: "eb-01", gameId: EB, prompt: "Energy tradeoff: 8 spoons today. Morning shift costs 5, interview prep costs 3, chores cost 2.", choices: ["Shift + prep; move chores to tomorrow", "All three and crash", "Skip the shift"], answer: "Shift + prep; move chores to tomorrow", difficulty: "beginner", criteria: "spend limited energy on fixed + high-value blocks" },
  { id: "eb-02", gameId: EB, prompt: "Energy tradeoff: noisy break room drains you; quiet corner restores you.", choices: ["Take breaks in the quiet corner", "Skip all breaks", "Breaks in the loudest spot"], answer: "Take breaks in the quiet corner", difficulty: "beginner", criteria: "choose restoring micro-environments" },
  { id: "eb-03", gameId: EB, prompt: "Energy tradeoff: double shift offered, but tomorrow is exam day.", choices: ["Decline the double; protect exam energy", "Take it and cram at 2am", "Take it and skip the exam"], answer: "Decline the double; protect exam energy", difficulty: "standard", criteria: "protect peak-demand days; decline stacked loads" },
  { id: "eb-04", gameId: EB, prompt: "Energy tradeoff: 2-hour commute vs 30-min earlier bus with a seat.", choices: ["Earlier bus: sit, plan the day, arrive calm", "Standing-room late bus", "Drive tired"], answer: "Earlier bus: sit, plan the day, arrive calm", difficulty: "standard", criteria: "trade small time for lower sensory load" },
  { id: "eb-05", gameId: EB, prompt: "Energy tradeoff: back-to-back errands across town after a closing shift.", choices: ["One errand tonight, rest after sleep", "All errands at midnight", "Skip sleep to finish"], answer: "One errand tonight, rest after sleep", difficulty: "beginner", criteria: "cap post-shift loads; batch after rest" },
  { id: "eb-06", gameId: EB, prompt: "Energy tradeoff: fluorescent lights trigger headaches by noon.", choices: ["Request a visor + 5-min shade breaks", "Squat through the pain daily", "Quit without asking"], answer: "Request a visor + 5-min shade breaks", difficulty: "standard", criteria: "request a specific low-cost accommodation" },
  { id: "eb-07", gameId: EB, prompt: "Energy tradeoff: group study (fun, draining) vs solo study (calm, effective).", choices: ["Solo 45 min, then 15 min group check-in", "3-hour group hangout", "No study at all"], answer: "Solo 45 min, then 15 min group check-in", difficulty: "standard", criteria: "front-load solo focus; time-box social learning" },
  { id: "eb-08", gameId: EB, prompt: "Energy tradeoff: phone scrolls eat 90 min before bed; mornings wrecked.", choices: ["Charger outside bedroom; lights out 10:30pm", "Scroll until 2am", "Delete sleep"], answer: "Charger outside bedroom; lights out 10:30pm", difficulty: "beginner", criteria: "guard sleep with a physical phone boundary" },
  { id: "eb-09", gameId: EB, prompt: "Energy tradeoff: heavy lunch = 2pm crash during register rush.", choices: ["Light protein lunch + water; snack at 3pm", "Skip eating all day", "Double portions at noon"], answer: "Light protein lunch + water; snack at 3pm", difficulty: "standard", criteria: "eat for steady afternoon output" },
  { id: "eb-10", gameId: EB, prompt: "Energy tradeoff: saying yes to every swap leaves zero rest days.", choices: ["One swap per week max; Sundays off", "Yes to everything", "No to everything forever"], answer: "One swap per week max; Sundays off", difficulty: "standard", criteria: "cap yeses with a weekly swap budget" },
  { id: "eb-11", gameId: EB, prompt: "Energy tradeoff: morning person offered permanent nights (+$1/hr).", choices: ["Stay on mornings; bank sleep over the differential", "Take nights and fail probation", "Take nights and nap on shift"], answer: "Stay on mornings; bank sleep over the differential", difficulty: "brisk", criteria: "price chronotype honestly against pay bumps" },
  { id: "eb-12", gameId: EB, prompt: "Energy tradeoff: 4 flights of stairs vs slow elevator at work.", choices: ["Elevator on shift days; stairs on off days", "Sprint stairs daily in pain", "Avoid all movement"], answer: "Elevator on shift days; stairs on off days", difficulty: "beginner", criteria: "spend joints/energy where the shift needs them" },
  { id: "eb-13", gameId: EB, prompt: "Energy tradeoff: back-to-back interviews with no gap.", choices: ["Insert 15-min reset walks between them", "Stack five in a row", "Cancel all"], answer: "Insert 15-min reset walks between them", difficulty: "brisk", criteria: "schedule reset gaps between high-stakes blocks" },
  { id: "eb-14", gameId: EB, prompt: "Energy tradeoff: loud concert night before 6am open.", choices: ["Skip or leave early; protect the open", "Front row until 1am", "Call out with no notice"], answer: "Skip or leave early; protect the open", difficulty: "beginner", criteria: "trade one fun night for shift reliability" },
  { id: "eb-15", gameId: EB, prompt: "Energy tradeoff: multitasking register + phone + chat = errors.", choices: ["Single-task: register first, phone on break", "Juggle all three live", "Ignore customers"], answer: "Single-task: register first, phone on break", difficulty: "standard", criteria: "single-task during error-prone work" },
  { id: "eb-16", gameId: EB, prompt: "Energy tradeoff: gym 90 min vs 20-min walk before shift.", choices: ["20-min walk; save gym for days off", "90-min leg day pre-shift", "No movement ever"], answer: "20-min walk; save gym for days off", difficulty: "standard", criteria: "match workout size to shift-day capacity" },
  { id: "eb-17", gameId: EB, prompt: "Energy tradeoff: caffeine after 4pm wrecks sleep; 3pm slump daily.", choices: ["Walk + water + daylight at 3pm; caffeine by noon only", "Espresso at 6pm", "Nap on the stockroom floor"], answer: "Walk + water + daylight at 3pm; caffeine by noon only", difficulty: "brisk", criteria: "beat slumps without borrowing from sleep" },
  { id: "eb-18", gameId: EB, prompt: "Energy tradeoff: family event runs late; early training tomorrow.", choices: ["Attend 1 hour, leave with a goodbye round", "Stay to midnight", "Skip both"], answer: "Attend 1 hour, leave with a goodbye round", difficulty: "standard", criteria: "time-box socials before fixed mornings" },
  { id: "eb-19", gameId: EB, prompt: "Energy tradeoff: perfectionist rewrite of one email for 40 min.", choices: ["Good-enough draft + checklist, send in 10 min", "Rewrite for another hour", "Never send emails"], answer: "Good-enough draft + checklist, send in 10 min", difficulty: "brisk", criteria: "cap perfection loops with done criteria" },
  { id: "eb-20", gameId: EB, prompt: "Energy tradeoff: weekend has chores, rest, friends — pick two fully.", choices: ["Rest + one social; chores split into 20-min bursts", "All three at 100%", "None; couch-lock"], answer: "Rest + one social; chores split into 20-min bursts", difficulty: "beginner", criteria: "budget weekends: rest + one joy + chunked chores" },
  { id: "eb-21", gameId: EB, prompt: "Energy tradeoff: hot warehouse; cooling vest helps but feels awkward.", choices: ["Wear the vest; comfort beats looks", "Overheat quietly", "Refuse water breaks"], answer: "Wear the vest; comfort beats looks", difficulty: "beginner", criteria: "use the accommodation that keeps you safe" },
  { id: "eb-22", gameId: EB, prompt: "Energy tradeoff: news doomscroll spikes anxiety before interviews.", choices: ["Mute news day-of; 5-min breathing routine", "Doomscroll in the lobby", "Wing it panicking"], answer: "Mute news day-of; 5-min breathing routine", difficulty: "standard", criteria: "cut pre-performance inputs; run a calm routine" },
];

export const vocrehabPack3Banks: Record<VocrehabPack3Game, readonly VocrehabBank3Item[]> = {
  "resume-rescue": resumeRescueBank,
  "inbox-sprint": inboxSprintBank,
  "schedule-juggle": scheduleJuggleBank,
  "paycheck-plan": paycheckPlanBank,
  "energy-budget": energyBudgetBank,
};

/** Deterministically draw up to n items for a game from a seed string. */
export function vocrehabDrawPack3(gameId: VocrehabPack3Game, seed: string, n: number): VocrehabPack3Draw {
  const bank = vocrehabPack3Banks[gameId] ?? [];
  const count = Math.max(0, Math.min(Math.floor(n), bank.length));
  const rand = mulberry32(xmur3(String(seed))());
  const items = shuffle(rand, bank).slice(0, count);
  const criteria: string[] = [];
  for (const item of items) {
    if (criteria.indexOf(item.criteria) === -1) criteria.push(item.criteria);
  }
  return { seed: String(seed), items, criteria };
}
