/* Emit TestingH (1920x1080) and TestingV (1080x1920) from one gameplay take. */
const fs=require('fs'),path=require('path'),{spawn}=require('child_process');const {mediaMogulFfmpeg}=require('../../lib/mediamogul_video_recorder');
const root=path.resolve(__dirname,'..','..'),input=path.resolve(process.argv[2]||'');if(!input||!fs.existsSync(input))throw Error('Usage: node export_testing_layouts.js <gameplay.mp4>');
// Desktop recorder sessions keep their video and manifest together, while
// older browser-capture sessions use data/browser-captures. Support both so
// every Vibecodeworker recording can receive the same diagnostic exports.
const id=path.basename(input,path.extname(input)),sessionDir=path.dirname(input),legacyDir=path.join(root,'data','browser-captures'),sessionManifest=path.join(sessionDir,'playtest-manifest.json'),legacyManifest=path.join(legacyDir,id+'.json'),dir=fs.existsSync(sessionManifest)?sessionDir:legacyDir,mPath=fs.existsSync(sessionManifest)?sessionManifest:legacyManifest;const m=fs.existsSync(mPath)?JSON.parse(fs.readFileSync(mPath)):{};const ev=m.events||[],inputs=ev.filter(e=>e.type==='input'||e.type==='action').slice(-10).map(e=>e.key||e.input||e.action?.type||'action').join(' | ')||'none',log=ev.some(e=>/error|rejection|bug-found/i.test(e.type))?'browser errors detected':'no browser errors';const ff=mediaMogulFfmpeg(root);const ffprobe=ff.replace(/ffmpeg(?:\.exe)?$/i,process.platform==='win32'?'ffprobe.exe':'ffprobe');const run=(a)=>new Promise((ok,no)=>{const p=spawn(ff,a,{windowsHide:true});let e='';p.stderr.on('data',x=>e+=x);p.on('close',c=>c?no(Error(e.slice(-1000))):ok())});
// -shortest never terminates against the infinite -loop overlay (the looped
// PNG has no EOF, so the muxer encodes forever). Cap the encode at the
// gameplay source duration instead, probed up front.
const probeDuration=(file)=>new Promise((ok,no)=>{const p=spawn(ffprobe,['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',file],{windowsHide:true});let o='';p.stdout.on('data',x=>o+=x);p.on('close',c=>c?no(Error('ffprobe failed')):ok(Number(o.trim())))});const probeDims=(file)=>new Promise((ok,no)=>{const p=spawn(ffprobe,['-v','error','-select_streams','v:0','-show_entries','stream=width,height','-of','csv=p=0',file],{windowsHide:true});let o='';p.stdout.on('data',x=>o+=x);p.on('close',c=>{if(c)return no(Error('ffprobe dims failed'));const[w,h]=String(o).trim().split(',').map(Number);ok({width:w,height:h})})});
(async()=>{const srcDuration=await probeDuration(input);if(!Number.isFinite(srcDuration)||srcDuration<=0)throw Error('could not probe gameplay duration');const dims=await probeDims(input).catch(()=>({width:0,height:0}));const landscape=Number(dims.width)>Number(dims.height);for(const mode of ['H','V']){const png=path.join(dir,id+'.testing'+mode+'.png'),out=path.join(dir,id+'.testing'+mode+'.mp4');await new Promise((ok,no)=>{const p=spawn('powershell',['-ExecutionPolicy','Bypass','-File',path.join(__dirname,'export_testing_layouts.ps1'),'-Mode',mode,'-Out',png,'-Game',id,'-Inputs',inputs,'-Log',log],{windowsHide:true});p.on('close',c=>c?no(Error('overlay generation failed')):ok())});let filter=mode==='H'?'[0:v]scale=1920:1080[base];[base][1:v]overlay=0:0:format=auto[v]':'[0:v]scale=900:-2[top];[0:v]scale=900:-2[mid];[top][mid]vstack=inputs=2[stack];[stack][1:v]overlay=0:0:format=auto[v]';
// A landscape desktop take stacks to a short wide strip; centering it on the
// 1080x1920 overlay canvas keeps the full diagnostics panel visible instead
// of cropping it away. Portrait takes keep the legacy direct overlay.
if(mode==='V'&&landscape)filter='[0:v]scale=900:-2[top];[0:v]scale=900:-2[mid];[top][mid]vstack=inputs=2[stack];[stack]pad=1080:1920:(ow-iw)/2:(oh-ih)/2[padded];[padded][1:v]overlay=0:0:format=auto[v]';const args=['-y','-i',input,'-loop','1','-i',png,'-filter_complex',filter,'-map','[v]','-map','0:a?','-t',srcDuration.toFixed(3),'-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-c:a','aac','-b:a','160k','-movflags','+faststart',out];await run(args);console.log(out)}m.layoutExports={testingH:path.join(dir,id+'.testingH.mp4'),testingV:path.join(dir,id+'.testingV.mp4'),branding:'4weird.com Shop.MattyJacks.com VibeCodeWorker.com MattyJacks.com'};fs.writeFileSync(mPath,JSON.stringify(m,null,2))})().catch(e=>{console.error(e.stack||e);process.exit(1)});
