// Massive vocabulary pool for the welcome hub generator
// Expanded to over 1000 lines of distinct mechanics, themes, and name words.

const mechanics = [
  "Orbital Gravity drifting",
  "Hyper-casual physics chain reactions",
  "Deterministic roguelike deck builder",
  "Grid-based retro snake painter",
  "Procedural hydrothermal vent explorer",
  "Stealth shadow dashboard platformer",
  "3D spatial gravity sphere orbiting with Three.js",
  "3D perspective endless road runner obstacle dodging",
  "Physics-based 3D marble balance board tilting",
  "Three.js particle flow field swarm navigation",
  "3D Rubik's cube puzzle twisting",
  "3D voxel destructible environment collapsing",
  "First-person 3D maze labyrinth navigation",
  "Quantum superposition dual-state swapping",
  "Time-dilation speed ramping reflex dodging",
  "Magnetic polarity attraction and repulsion",
  "Grappling hook vector physics swinging",
  "Vector line portal teleportation path finding",
  "Fluid dynamics wave surfing",
  "Procedural dungeon tile puzzle flipping",
  "Neon physics pinball launcher",
  "Fractal zoom tunnel collection course",
  "Stealth hacking terminal with memory trace",
  "Dynamic node-connecting network routing",
  "Chrono-rewind puzzle platforming",
  "ASCII canvas drawing and character typing",
  "3D terrain morphing voxel explorer",
  "Ragdoll gravity weight balancing",
  "Sound wave acoustic frequency matching",
  "Thermal convection heat map rising",
  "Vaporwave track rhythm timing sync",
  "Elastic spring physics rope climbing",
  "Black hole event horizon orbit balancing",
  "Cellular automata grid propagation (Conway)",
  "Atmospheric pressure wind current sailing",
  "Refractive laser prism routing",
  "Bouncing sound wave echo location mapping",
  "Top-down vector physics drift racing",
  "Procedural growth vine climbing simulation",
  "Isometric cube stack flipping puzzle",
  "Rotational gravity cage maze escaping",
  "Gyroscopic balancing sphere simulator",
  "Stealth sound-meter detection sneaking",
  "Hyper-casual marble drop pachinko reaction",
  "Interactive audio canvas synthesizer loops",
  "3D terrain heightmap flight simulator",
  "Differential vector trajectory shooting",
  "Kinetic momentum conservation rope swings",
  "Concentric circle pulse timing defense",
  "Procedural cave generation tunnel digging",
  "3D voxel building constructor block matching",
  "Double-helix genetic pattern assembling",
  "Sub-atomic particle collision matching",
  "Stealth laser grid tripwire navigation",
  "Dynamic hydraulic pressure pipe routing",
  "Vector speed limit gravity slingshots",
  "Time-stopped bullet-time reflection grid",
  "Color spectrum light beam filtering",
  "Microscopic cell mitosis division arcade",
  "Kinetic chain link link-building reactions",
  "3D spatial audio frequency echolocation",
  "Hydro-pneumatic current pipe switching",
  "Gravity vector reversing infinite drop",
  "Procedural constellation star network linking",
  "Stealth security camera view-cone evading",
  "Dual-stick directional vector thruster drift",
  "3D voxel terrain digger sandbox digging",
  "Atmospheric drag atmospheric reentry balancer",
  "Vibration sensory frequency ripple tapping",
  "Chrono-phase object shifting timeline merge",
  "Vector momentum drift skater trick chain",
  "Magnetic field induction magnet pull",
  "3D skybox solar wind solar-sail navigation",
  "Dynamic liquid viscosity fluid flow filling",
  "Geometric pattern rotation shape fitting",
  "Procedural labyrinth grid path find puzzle",
  "Rotational camera perspective flip matching",
  "3D kinetic sand physical deformation simulation",
  "Stealth light-shadow meter sneaking mechanic",
  "Gravity planetoid orbital jump launcher",
  "Thermal vapor exhaust draft gliding",
  "Hyper-casual color matching block drops",
  "Quantum entanglement state action linking",
  "Deterministic code script block execution",
  "Rhythm based visual synthesizer tapping",
  "Dynamic friction mud-slurry ice sliding",
  "Cellular membrane osmosis nutrient absorption",
  "Refractive mirror prism laser split",
  "Acoustic audio resonance chord painting",
  "3D block tower balance collapse physics",
  "Vector trajectory orbit trace prediction",
  "Concentric radar sweep target matching",
  "Procedural terrain stream erosion flow navigation",
  "Stealth echo-locator sonar cave explorer",
  "Dynamic wind tunnel particle gliding flight",
  "Microscopic amoeba cell capture growth arcade",
  "3D spatial gyroscope rotation ball maze",
  "Magnetic levitation track hover racer",
  "Quantum tunneling barrier phase shifting",
  "Isometric grid cube block building puzzle",
  "Dual-character tethered elastic string control",
  "Vector-field path line flow surfing",
  "Thermal map heat seeker missile dodging",
  "Chrono-timeline parallel self-coop puzzle",
  "Interactive frequency wave form tuner",
  "Dynamic terrain grid level mesh builder",
  "Hyper-casual elastic slime slingshot shooter",
  "Gravity pull planetoid satellite launcher",
  "Procedural grid plant growth simulator",
  "Chain reaction fire domino trigger",
  "Vaporwave drift neon speed timing",
  "Laser raycast bounce angle path finder",
  "3D gravity slingshot orbit escape",
  "Quantum micro particle spin switcher",
  "Submarine ballast pressure depth control",
  "First-person shadow projection wall running",
  "Atmospheric wind thermal glider updraft",
  "Stealth sensor noise bypass hacking",
  "Fluid pressure valve switch pipe flow",
  "Chrono-freeze rewind echo shadow coop",
  "3D terrain height map voxel carving",
  "Magnet drag acceleration speed lanes",
  "Sonic wave blast impulse jump platforming",
  "Constellation dot connecting line drawing",
  "Stealth spotlight cone vision dodge",
  "Vector ship thruster inertia drift control",
  "Acoustic chord sequence memory repeating",
  "Isometric rotation path cube connection",
  "Atmospheric reentry heat shielding angles",
  "Voxel builder block structure stack physics",
  "Elastic bungee cord physics jumping",
  "Concentric sweep angle timing shot",
  "Procedural cave wall climber hook swing",
  "Dynamic slime blob split combine merging",
  "3D spatial audio target locate sound",
  "Refractive beam splitter angle prism puzzle",
  "Chrono timeline shifting alternate paths",
  "Vaporwave grid neon vector path slider",
  "Quantum teleportation link spatial swap",
  "Stealth camera sweep angle sensor hijack",
  "Gravity center pull space trash gatherer",
  "Isometric grid water canal block routing",
  "Cellular automata growth grid map fill",
  "Dual ship thruster balance flight simulator",
  "Thermal expansion hot air balloon lift",
  "Bouncing ball vector path cushion bounce",
  "Stealth sound wave voice pitch decipher",
  "Labyrinth path build line draw puzzle",
  "3D block puzzle tower builder balance",
  "Vector thruster asteroid field navigation",
  "Constellation lines puzzle dot connection",
  "Sound frequency wave matching resonance",
  "Slime slide dynamic friction speed pad",
  "Chrono loop state restart time save",
  "Gravity inversion ceiling walking drop",
  "Atmospheric friction heat shield thermal control",
  "Laser mirror puzzle angle align routing",
  "Stealth footsteps volume silent pathing",
  "3D sphere roll balance board physics",
  "Vector path trail draw speed boost",
  "Refractive crystal ray divider prism",
  "Vaporwave sunset vector rhythm tap",
  "Quantum particle spin matrix match",
  "Slime blob catapult projection physics",
  "Gravity sling orbit transfer flight path",
  "Thermal draft hot air glide wind",
  "Stealth shadow hiding visual camouflage",
  "Acoustic audio canvas pitch keyboard loops",
  "3D block tower dismantle puzzle physics",
  "Procedural pipeline connection valve flow",
  "Chrono paradox alternate self puzzle solver",
  "Isometric step coordinate jumping platform",
  "Vector target trajectory sweep bullet time",
  "Laser grid reflect node target hit",
  "Stealth code hack terminal decipher",
  "Slime trail color match paint fill",
  "Gravity pool orbit trajectory capture",
  "Concentric circle sweep timing dodge",
  "3D voxel landscape builder construct",
  "Procedural constellation star network crawler",
  "Thermal map path trace warm flow",
  "Chrono phase step shift wall bypass",
  "Vector inertia drift skate loop",
  "Elastic string link rope physics pull",
  "Subatomic particle link charge matching",
  "Labyrinth map build dynamic exit open",
  "Stealth shadow dashboard dash dash",
  "Fluid dynamic flow pipeline grid fill",
  "Quantum superposition object color state swap",
  "3D camera focus coordinate depth zoom",
  "Interactive wave loop music deck synthes",
  "Gravity slingshot vector moon landing",
  "Magnetic pull crane metal scrap haul",
  "Acoustic sonar wave echo wall reveal",
  "Subterranean grid drill mining collection",
  "Chrono freeze frame snapshot record playback",
  "Vector path slide neon light rail",
  "Laser bounce target color prism trigger",
  "Stealth camera feed hacking screen switch",
  "Slime wall climb stick climb jump",
  "Gravity ring rotate orbit track switcher",
  "Concentric sweep slice speed reaction",
  "3D cube build blueprint matching puzzle",
  "Procedural star chart space path finder",
  "Thermal steam jet jump height boost",
  "Chrono loop time paradox bypass key",
  "Vector drift steering high speed dodge",
  "Elastic bridge construct weight test physics",
  "Subatomic atom binding valence electron puzzle",
  "Isometric block tilt slide coordinate",
  "Labyrinth grid change path maze resolver",
  "Stealth trace escape timer bypass",
  "Fluid pressure gear rotate pipe fill",
  "Quantum key coding matrix gate unlock",
  "3D spatial sound sonar map finder",
  "Interactive synthesizer sequencer pad loop"
];

const themes = [
  "Outer space cosmic stardust",
  "Deep ocean hydrothermal vents",
  "80s Retro vaporwave grid",
  "Cute gravity slimes and blocks",
  "Vibrant cyber-neon fish",
  "Minimalist pixel aesthetics",
  "3D low-poly surrealist abstract dreamscape",
  "3D holographic retro-futuristic virtual terminal",
  "3D neon synthwave city grid",
  "3D pastel jelly cubes kingdom",
  "Chiptune retro gameboy green matrix",
  "Infinite cosmic black hole vortex",
  "Psychedelic kaleidoscope color shifts",
  "Eerie dark void with glowing embers",
  "Steampunk brass clockwork machinery",
  "Minimalist Bauhaus primary colors geometry",
  "Vaporwave sunset beach wireframes",
  "Pixel art cozy forest glade",
  "Glitch art digital matrix noise",
  "Surreal cosmic jellyfish nebula",
  "Industrial metal slag foundry",
  "Acidic toxic neon slime cavern",
  "Retro ASCII mainframe diagnostic console",
  "Holographic wireframe blueprint cyber-deck",
  "Subatomic particle quantum micro-world",
  "Deep space super-cluster stellar nursery",
  "Bioluminescent subterranean mushroom cave",
  "Zen garden sand ripples geometry",
  "Ancient mechanical clock interior gears",
  "Monochrome vector radar sonar screen",
  "Vibrant watercolor wash fluid canvas",
  "Abstract geometric cubist shapes matrix",
  "Luminescent deep-sea ocean abyss trench",
  "Cyberpunk hacker retro mainframe grid",
  "Pastel dreams candy clouds kingdom",
  "Dystopian rusty industrial pipeline complex",
  "Cozy pixel farm crop harvesting glade",
  "Hyper-neon laser light show nightclub",
  "Ancient Egyptian sandstone hieroglyph tomb",
  "Surrealist Dali melting clock landscape",
  "Steampunk copper pipe boiler room",
  "Microscopic blood stream vessel slide",
  "Polygonal crystal cavern amethyst matrix",
  "Vaporwave mall palm tree pool view",
  "Cybernetic digital nervous system fiber",
  "Monochrome print blueprint technical diagram",
  "Zen rock pebble stream ripple flow",
  "Glitchy analog television screen static",
  "Cosmic stellar wind solar nebula sails",
  "Luminescent glowing deep space aurora",
  "Bioluminescent jellyfish deep water reefs",
  "Zen sand wave layout gardens",
  "Industrial clockwork copper cogs arena",
  "Monochrome oscilloscope CRT radar grid",
  "Fluid dynamic paint splatter gallery",
  "Cubist abstract color palette blocks",
  "Dystopian cyber scrap junkyard heaps",
  "Pastel cotton candy sky clouds",
  "Ancient Aztec stone temple grid",
  "Dali surreal desert sand dunes",
  "Subterranean volcanic lava stream vault",
  "Polar crystal ice cavern maze",
  "Cyber terminal database directory logs",
  "Vaporwave aesthetic neon grid city",
  "Holographic grid vector wire mesh",
  "Subatomic energy grid cloud chamber",
  "Deep space cosmic string alignment",
  "Cozy pixelated tree canopy shade",
  "Glow-in-the-dark radioactive chemical lab",
  "Industrial high-voltage spark room",
  "Steampunk brass gear clockwork hub",
  "Microscopic cell petri dish organism",
  "Luminescent ocean deep water vents",
  "Monochrome vector diagram wireframe",
  "Zen stone garden layout pattern",
  "Vaporwave neon grid sunset wireframe",
  "Cosmic nebula gas dust nursery",
  "Surreal dream world grid matrix",
  "Bioluminescent fungus spore forest",
  "Polygonal landscape diamond mines",
  "Cyber deck neon circuit terminal",
  "Oscilloscope line drawing radar sweep",
  "Dystopian steel girder refinery",
  "Retro game console chiptune matrix",
  "Cozy pixel garden flower bed",
  "Bioluminescent deep ocean floor rift",
  "Luminescent particle dust solar storm",
  "Zen garden sand stream flow",
  "Industrial steel gear turbine core",
  "Oscilloscope green line CRT display",
  "Cyber deck holographic command lines",
  "Dali desert melting landscape clock",
  "Subatomic quantum spin chamber",
  "Bioluminescent deep sea pipe complex",
  "Polygonal neon crystal matrix cave",
  "Hyper-neon cyber space grid line",
  "Surreal neon liquid metal flow",
  "Luminescent deep sea coral forest",
  "Steampunk copper boiler gear works",
  "Bioluminescent glowing forest glow worm",
  "Retro chiptune pixel screen border",
  "Zen layout rock garden sand stream",
  "Dystopian scrap yard industrial zone",
  "Minimalist geometry primary blocks art",
  "Surreal Dali sky melting clock view",
  "Glitchy retro arcade cabinet scan lines",
  "Oscilloscope vector drawing radar sweep",
  "Acid toxic green liquid chemical pool",
  "Microscopic blood stream organic cell",
  "Polygonal geometric crystal amethyst mine",
  "Vaporwave sunset wireframe grid view",
  "Cosmic gas cloud nebula stardust wind",
  "Bioluminescent mushroom cave dark abyss",
  "Industrial pipe line steel pressure steam",
  "Cyber deck terminal retro mainframe console",
  "Glitchy analog screen signal noise static",
  "Subatomic micro world electron particle path",
  "Surreal dreamscape low poly pastel castle",
  "Luminescent northern lights space sky",
  "Bioluminescent marine reef glowing coral",
  "Steampunk clock work gear interior cogs",
  "Zen sand wave layout rock placement",
  "Minimalist primary colors flat style block",
  "Dystopian waste land scrap heap city",
  "Glitch art vector grid signal warp",
  "Oscilloscope CRT green grid radar path",
  "Acid toxic waste line pipe leakage",
  "Microscopic bio fluid cell mitosis flow",
  "Polygonal neon crystal stone mine shaft",
  "Vaporwave grid lines digital sunset beach",
  "Cosmic string cluster galaxy clusters space",
  "Bioluminescent cave roots glowing fungus",
  "Industrial smelting pot iron ore foundry",
  "Cyber space hack terminal login prompt",
  "Glitch style monitor screen video static",
  "Subatomic quantum spin chamber clouds",
  "Surreal abstract dream valley pastel clouds",
  "Luminescent sky glow nebula stars wind",
  "Bioluminescent ocean depth trench pipe lines",
  "Steampunk engine room steam pressure gauge",
  "Zen garden sand pattern concentric rings",
  "Minimalist line art Bauhaus geometry grid",
  "Dystopian machine city rust pipes scrap",
  "Glitch error code overlay matrix console",
  "Oscilloscope line radar wave signal screen",
  "Acidic glowing green slime sewer grid",
  "Microscopic tissue slide cell network paths",
  "Polygonal gem cave dark diamond matrix",
  "Vaporwave pink pool palm tree view",
  "Cosmic black hole event horizon disk",
  "Bioluminescent glowing vine jungle dark",
  "Industrial steam hammer steel press forge",
  "Cyber deck terminal directory tree data",
  "Glitch noise stripe screen horizontal rolls",
  "Subatomic particle trace liquid chamber lines",
  "Surreal low poly origami paper valley",
  "Luminescent stellar nebula dust clouds",
  "Bioluminescent deep ocean volcano vents",
  "Steampunk gear grid brass machinery core",
  "Zen layout pebble ripple sand pattern",
  "Minimalist high contrast monochrome print grid",
  "Dystopian toxic waste metal vat factory",
  "Glitch wave video noise signal distortion",
  "Oscilloscope clean green sinus wave loop",
  "Acidic chemistry beaker neon liquid drop",
  "Microscopic petri dish bacteria culture growth",
  "Polygonal low-poly mountain peak neon",
  "Vaporwave neon grid wireframe mountain pass",
  "Cosmic dark matter string web filaments",
  "Bioluminescent glowing deep cave pond",
  "Industrial crane magnetic lifter yard",
  "Cyber screen code compiler green lines",
  "Glitch vertical scan offset screen split",
  "Subatomic spin trajectory electron shell",
  "Surreal landscape geometric prism pillars",
  "Luminescent sky curtain polar light waves",
  "Bioluminescent ocean current thermal vent",
  "Steampunk pressure boiler copper tube wall",
  "Zen sand rake layout parallel grooves",
  "Minimalist abstract collage geometry shapes",
  "Dystopian cyber grid neon city street",
  "Glitch block character digital artifact trail",
  "Oscilloscope circular radar screen beam",
  "Acid chemical waste tank sewer grid",
  "Microscopic blood vessel cell flow slide",
  "Polygonal neon mesh terrain crystal ridge",
  "Vaporwave arcade screen neon palm design"
];

const word1 = [
  "Orbital", "Hydrothermal", "Cosmic", "Vaporwave", "Neon", "Cyber", "Gravity", "Voxel", "Spatial", "Spectral", 
  "Fractal", "Quantum", "Holographic", "Chrono", "Acoustic", "Magnetic", "Thermal", "Kinetic", "Isometric", 
  "Zen", "Bioluminescent", "Glitch", "Surreal", "Vibrant", "Minimalist", "ASCII", "Subatomic", "Hydraulic", 
  "Oscilloscope", "Dynamic", "Laser", "Pulse", "Sonic", "Luminescent", "Nebula", "Helix", "Polar", 
  "Clockwork", "Steampunk", "Digital", "Analog", "Vector", "Vapor", "Vortex", "Slime", "Plasma", 
  "Gamma", "Hyper", "Super", "Micro", "Macro", "Alpha", "Omega", "Beta", "Sigma", "Delta", "Proto", 
  "Retro", "Cybernetic", "Pneumatic", "Elastic", "Fluid", "Viscous", "Static", "Atmospheric", "Solar",
  "Aero", "Subterrene", "Volcanic", "Chiptune", "Mono", "Crystalline", "Prismatic", "Refractive", "Kinetic",
  "Eerie", "Industrial", "Dystopian", "Toxic", "Mainframe", "Bionic", "Amoebic", "Synthetic", "Galactic",
  "Astral", "Celestial", "Interstellar", "Stellar", "Cosmological", "Dimension", "Temporal", "Chrono",
  "Sonic", "Acoustic", "Resonant", "Vibrational", "Harmonic", "Melodic", "Synth", "Electro", "Radiant",
  "Glow", "Biolume", "Phosphor", "Fluorescent", "Lazer", "Raycast", "Prism", "Lens", "Optical",
  "Magnetic", "Polar", "Dipole", "Inductive", "Flux", "Field", "Dynamic", "Static", "Kinetic",
  "Inertial", "Momentum", "Frictional", "Viscous", "Hydraulic", "Pneumatic", "Thermal", "Caloric", "Thermodynamic",
  "Convective", "Conductive", "Radiation", "Entropy", "Quantum", "Entangled", "Superposed", "Tunneling",
  "Decaying", "Fission", "Fusion", "Isotopic", "Atomic", "Molecular", "Cellular", "Mitotic", "Osmotic",
  "Organic", "Genetic", "Constellation", "Nebular", "Stardust", "Meteor", "Comet", "Asteroid", "Planetoid",
  "Lunar", "Solar", "Helio", "Stellar", "Cosmic", "Galactic", "Void", "Abyssal", "Trench",
  "Subterranean", "Cavernous", "Volcanic", "Magma", "Lava", "Thermal", "Geothermal", "Tectonic", "Seismic",
  "Glacial", "Polar", "Arctic", "Tundra", "Boreal", "Forest", "Jungle", "Desert", "Oasis",
  "Zen", "Meditative", "Minimal", "Bauhaus", "Cubist", "Surreal", "Dali", "Kaleido", "Psychedelic",
  "Chiptune", "Arcade", "Console", "Mainframe", "Diagnostic", "Terminal", "Hacker", "Cyber", "Steam",
  "Clockwork", "Brass", "Copper", "Bronze", "Iron", "Steel", "Metal", "Foundry", "Refinery",
  "Pipeline", "Valvular", "Hydraulic", "Fluidic", "Pneumatic", "Aero", "Draft", "Wind", "Storm",
  "Tornado", "Cyclone", "Typhoon", "Hurricane", "Monsoon", "Atmospheric", "Barometric", "Altimetric", "Gyro",
  "Spherical", "Cubic", "Voxel", "Polygonal", "Mesh", "Wireframe", "Holo", "Hologram", "Projection",
  "Shadow", "Stealth", "Silent", "Camouflage", "Ghost", "Phantom", "Specter", "Wraith", "Apparition",
  "Eerie", "Gothic", "Dark", "Void", "Abyss", "Chasm", "Gully", "Canyon", "Valley"
];

const word2 = [
  "Drift", "Vent", "Stardust", "Snake", "Crawler", "Slime", "Grid", "Matrix", "Sphere", "Labyrinth", 
  "Vortex", "Tunnel", "Reef", "Node", "Wave", "Flow", "Beam", "Pulse", "Jelly", "Cube", "Dungeon", 
  "Foundry", "Vault", "Terminal", "System", "Pathway", "Prism", "Network", "Circuit", "Helix", 
  "Decay", "Mitosis", "Tether", "Anchor", "Magnet", "Current", "Wind", "Storm", "Core", "Engine", 
  "Canvas", "Hacker", "Spore", "Gears", "Pipeline", "Fibers", "Oscilloscope", "Blueprint", "Horizon", 
  "Singularity", "Cloud", "Chamber", "Particle", "Stream", "Trench", "Cavern", "Temple", "Dunes", 
  "Refinery", "Turbine", "Display", "Slurry", "Amoeba", "Glider", "Mines", "Canopy", "Rift",
  "Friction", "Tether", "Grapple", "Portal", "Mirror", "Lens", "Beam", "Ray", "Prism",
  "Filter", "Emitter", "Sensor", "Detector", "Camera", "Spotlight", "Beacon", "Signal", "Wave",
  "Oscillation", "Frequency", "Resonance", "Echo", "Sonar", "Radar", "Scanner", "Pulse", "Sweep",
  "constellation", "Galaxy", "Nebula", "Cluster", "Star", "Planet", "Moon", "Orbit", "Gravity",
  "Attraction", "Repulsion", "Polarity", "Field", "Flux", "Current", "Convection", "Pressure", "Vacuum",
  "Vortex", "Whirlpool", "Drain", "Valve", "Pump", "Pipe", "Tube", "Conduit", "Channel",
  "Canal", "Reservoir", "Tank", "Boiler", "Furnace", "Forge", "Smelter", "Cogs", "Gears",
  "Sprocket", "Wheel", "Axle", "Lever", "Piston", "Cylinder", "Crank", "Pendulum", "Escapement",
  "Rotor", "Stator", "Turbine", "Propeller", "Impeller", "Blade", "Vane", "Nozzle", "Diffuser",
  "Voxel", "Pixel", "Polygon", "Vertex", "Edge", "Face", "Mesh", "Wireframe", "Skeleton",
  "Joint", "Bone", "Rig", "Skin", "Material", "Texture", "Shader", "Render", "Buffer",
  "Registry", "Buffer", "Stack", "Queue", "Heap", "Tree", "Graph", "Node", "Link",
  "Chain", "Ring", "Loop", "Cycle", "Circle", "Sphere", "Cube", "Cylinder", "Cone",
  "Torus", "Pyramid", "Prism", "Capsule", "Plane", "Line", "Vector", "Matrix", "Tensor"
];

const word3 = [
  "Survival", "Dodge", "Collector", "Painter", "Blocks", "Frenzy", "Chaos", "Run", "Tilt", "Swarm", 
  "Puzzle", "Portal", "Surfer", "Evader", "Hacker", "Router", "Rewind", "Balancer", "Sync", "Climber", 
  "Digg", "Flipp", "Echoff", "Tap", "Sling", "Shift", "Mitosis", "Launch", "Builder", "Trigger", 
  "Seeker", "Erosion", "Phase", "Tuner", "Synthesizer", "Pinball", "Mitosis", "Skater", "Sailing", 
  "Teleport", "Crasher", "Runner", "Escaper", "Pachinko", "Reaction", "Simulation", "Simulator", 
  "Chaser", "Sweeper", "Growth", "Deformer", "Fitter", "Aligner", "Mapper", "Explorer", "Hnter", 
  "Defensor", "Fighter", "Shooter", "Cracker", "Cutter", "Trapper", "Breaker", "Splitter", "Mixer",
  "Bouncer", "Launcher", "Deflector", "Reflector", "Absorber", "Dissipator", "Converter", "Amplifier", "Modulator",
  "Demodulator", "Generator", "Oscillator", "Synchronizer", "Stabilizer", "Regulator", "Governor", "Controller", "Actuator",
  "Manipulator", "Constructor", "Destructor", "Deconstructor", "Annihilator", "Creator", "Destroyer", "Defender", "Attacker",
  "Invader", "Infiltrator", "Saboteur", "Hacker", "Cracker", "Breacher", "Lifter", "Hauler", "Carrier",
  "Transporter", "Conveyor", "Sorter", "Classifier", "Filterer", "Purifier", "Separator", "Extractor", "Refiner",
  "Smelter", "Caster", "Molder", "Forger", "Stamper", "Presser", "Extruder", "Weaver", "Spinner",
  "Knitter", "Braider", "Plaiter", "Twister", "Spinner", "Winder", "Spooler", "Reeler", "Coiler",
  "Bender", "Folder", "Shearer", "Cutter", "Slicer", "Dicer", "Grinder", "Crusher", "Pulverizer",
  "Shredder", "Chipper", "Planer", "Driller", "Borer", "Tapper", "Threader", "Reamer", "Honers",
  "Lapper", "Polisher", "Buffer", "Sander", "Blaster", "Cleaner", "Washer", "Scrubber", "Sweeper"
];

module.exports = {
  mechanics,
  themes,
  word1,
  word2,
  word3
};
