// GraveGain food roster: all 127 consumable emojis (v2 layer catalog truth).
//
// Each entry fixes ONE effect kind + tier for that emoji across gravegain1d,
// gravegain2d and gravegain3d (endless, mission, mmorpg). Numbers are derived
// per game/mode by deriveFoodStats() in @/lib/gravegain-food — batch files in
// this folder add the 3x3 stat tables plus drop notes. Emoji codepoints below
// are exact (including VS16/ZWJ sequences); batch validators fail on drift.
//
// Blurbs stay playful-neutral on purpose: the same item shows in kid, teen
// and all content modes, so no profanity, no alcohol words, no drug lore.
// Brews and wines are named as fantasy juices, ciders and tonics.

import type { GraveGainFoodRosterEntry } from "@/lib/gravegain-food";

export const GRAVEGAIN_FOOD_ROSTER: readonly GraveGainFoodRosterEntry[] = [
  { id: "grave-grapes", name: "Grave Grapes", emoji: "🍇", blurb: "Shadow-sweet grapes from the crypt arbor. Pop them mid-fight.", effect: "heal", tier: 1 },
  { id: "wraith-melon", name: "Wraith Melon", emoji: "🍈", blurb: "Pale melon that tastes like cold mist. Light and restoring.", effect: "heal", tier: 1 },
  { id: "crypt-watermelon", name: "Crypt Watermelon", emoji: "🍉", blurb: "A whole red slab of dungeon hydration. Big juicy heal.", effect: "heal", tier: 2 },
  { id: "ember-orange", name: "Ember Orange", emoji: "🍊", blurb: "Warm citrus that glows faintly. Peels fast, heals fast.", effect: "heal", tier: 1 },
  { id: "lantern-lemon", name: "Lantern Lemon", emoji: "🍋", blurb: "Sour enough to wake the dead — sharpens your focus.", effect: "focus", tier: 1 },
  { id: "bog-banana", name: "Bog Banana", emoji: "🍌", blurb: "Mushy bog banana. Ugly, filling, and weirdly comforting.", effect: "heal", tier: 1 },
  { id: "crypt-pineapple", name: "Crypt Pineapple", emoji: "🍍", blurb: "Spiked golden fruit from the deep grove. A hearty feast-snack.", effect: "heal", tier: 2 },
  { id: "marrow-mango", name: "Marrow Mango", emoji: "🥭", blurb: "Honeyed mango of the marrow orchards. Restores vitality.", effect: "heal", tier: 2 },
  { id: "orchard-apple", name: "Orchard Apple", emoji: "🍎", blurb: "Crisp red apple from the surface orchards. A classic field snack.", effect: "heal", tier: 1 },
  { id: "sour-wisp-apple", name: "Sour Wisp Apple", emoji: "🍏", blurb: "Green apple with a ghostly tang. Wakes you right up.", effect: "heal", tier: 1 },
  { id: "ghost-pear", name: "Ghost Pear", emoji: "🍐", blurb: "Translucent pear that hums softly. Gentle healing.", effect: "heal", tier: 1 },
  { id: "velvet-peach", name: "Velvet Peach", emoji: "🍑", blurb: "Fuzzy peach with golden juice. A tender, generous heal.", effect: "heal", tier: 2 },
  { id: "blood-cherries", name: "Blood Cherries", emoji: "🍒", blurb: "Dark cherries with a tart bite. Sweet blood for the living.", effect: "heal", tier: 2 },
  { id: "bramble-strawberry", name: "Bramble Strawberry", emoji: "🍓", blurb: "Sun-ripe berries from the thorn rows. Small, sweet, strong.", effect: "heal", tier: 2 },
  { id: "star-blueberries", name: "Star Blueberries", emoji: "🫐", blurb: "Tiny berries that glitter like constellations. Mind-sharpening.", effect: "focus", tier: 2 },
  { id: "dungeon-kiwi", name: "Dungeon Kiwi", emoji: "🥝", blurb: "Fuzzy brown outside, bright green inside. Zesty little heal.", effect: "heal", tier: 1 },
  { id: "heart-tomato", name: "Heart Tomato", emoji: "🍅", blurb: "Plump red tomato, warm from the grow-lamps. Simple and good.", effect: "heal", tier: 1 },
  { id: "brine-olive", name: "Brine Olive", emoji: "🫒", blurb: "Salty olive that leaves a protective film. A briny little ward.", effect: "shield", tier: 1 },
  { id: "iron-coconut", name: "Iron Coconut", emoji: "🥥", blurb: "Crack it open for sweet milk and a hard-shell ward.", effect: "shield", tier: 2 },
  { id: "spore-cap", name: "Spore Cap Mushroom", emoji: "🍄", blurb: "Common dungeon cap. Its spores knit a thin protective veil.", effect: "shield", tier: 1 },
  { id: "bog-avocado", name: "Bog Avocado", emoji: "🥑", blurb: "Buttery green flesh. Cushions blows like a soft pillow.", effect: "shield", tier: 1 },
  { id: "night-eggplant", name: "Night Eggplant", emoji: "🍆", blurb: "Glossy purple vegetable with a meaty bite. Steady strength.", effect: "power", tier: 1 },
  { id: "dirt-potato", name: "Dirt Potato", emoji: "🥔", blurb: "Humble crypt potato. Baked over bonefire coals, deeply filling.", effect: "heal", tier: 1 },
  { id: "lantern-carrot", name: "Lantern Carrot", emoji: "🥕", blurb: "Crunchy orange carrot. Sharpens eyes and quickens feet.", effect: "haste", tier: 1 },
  { id: "gold-corn", name: "Gold Corn", emoji: "🌽", blurb: "Buttered dungeon corn on the cob. Sweet, warm, restoring.", effect: "heal", tier: 1 },
  { id: "dragon-pepper", name: "Dragon Pepper", emoji: "🌶️", blurb: "A pepper with actual fire in it. Rage in vegetable form.", effect: "power", tier: 2 },
  { id: "swift-pepper", name: "Swift Bell Pepper", emoji: "🫑", blurb: "Crisp green pepper. Light crunch that hurries your steps.", effect: "haste", tier: 1 },
  { id: "cool-cucumber", name: "Cool Cucumber", emoji: "🥒", blurb: "Ice-crisp cucumber. Cools burns and calms wounds.", effect: "heal", tier: 1 },
  { id: "grave-lettuce", name: "Grave Lettuce", emoji: "🥬", blurb: "Dewy greens from the crypt garden. Clean and soothing.", effect: "heal", tier: 1 },
  { id: "iron-broccoli", name: "Iron Broccoli", emoji: "🥦", blurb: "Dense little trees of iron and fiber. A green ward.", effect: "shield", tier: 1 },
  { id: "vampire-garlic", name: "Vampire Garlic", emoji: "🧄", blurb: "The classic ward against the risen. Evil hates the smell.", effect: "shield", tier: 2 },
  { id: "ogre-onion", name: "Ogre Onion", emoji: "🧅", blurb: "Makes you cry, makes blades slide off. Layered protection.", effect: "shield", tier: 1 },
  { id: "mighty-peanut", name: "Mighty Peanut", emoji: "🥜", blurb: "Tiny nut, huge protein. A pocket-sized power-up.", effect: "power", tier: 1 },
  { id: "hex-beans", name: "Hex Beans", emoji: "🫘", blurb: "Speckled beans humming with stored spells. Hearty strength.", effect: "power", tier: 1 },
  { id: "golem-chestnut", name: "Golem Chestnut", emoji: "🌰", blurb: "Roasted chestnut, hard as a golem knuckle. A sturdy ward.", effect: "shield", tier: 1 },
  { id: "warming-ginger", name: "Warming Ginger", emoji: "🫚", blurb: "Fiery root that heats your blood. Move like warm wind.", effect: "haste", tier: 2 },
  { id: "pod-peas", name: "Pod Peas", emoji: "🫛", blurb: "Sweet peas that pop between your teeth. Light and quickening.", effect: "haste", tier: 1 },
  { id: "sootcap", name: "Sootcap Mushroom", emoji: "🍄‍", blurb: "Rare soot-dark cap from the ash vents. A thick spore ward.", effect: "shield", tier: 2 },
  { id: "grave-root", name: "Grave Root Vegetable", emoji: "🫜", blurb: "Pale root pulled from old gravesoil. Deep, earthy healing.", effect: "heal", tier: 2 },
  { id: "bonefire-bread", name: "Bonefire Bread", emoji: "🍞", blurb: "Crusty loaf baked over bonefire coals. The dungeon staple.", effect: "heal", tier: 1 },
  { id: "goblin-croissant", name: "Goblin Croissant", emoji: "🥐", blurb: "Impossibly flaky goblin pastry. Eaten in three quick bites.", effect: "haste", tier: 1 },
  { id: "crypt-baguette", name: "Crypt Baguette", emoji: "🥖", blurb: "A baguette you could parry with — then eat. Crusty strength.", effect: "power", tier: 1 },
  { id: "traveler-flatbread", name: "Traveler Flatbread", emoji: "🫓", blurb: "Flat, warm, packable. A wanderer's reliable ward-snack.", effect: "shield", tier: 1 },
  { id: "knot-pretzel", name: "Knot Pretzel", emoji: "🥨", blurb: "Salted knot as tough as dungeon rope. Chewy protection.", effect: "shield", tier: 1 },
  { id: "spire-bagel", name: "Spire Bagel", emoji: "🥯", blurb: "Dense ring from the spire bakeries. Filling and honest.", effect: "heal", tier: 1 },
  { id: "coin-pancakes", name: "Coin Pancakes", emoji: "🥞", blurb: "Golden stack drowned in syrup. Breakfast of champions.", effect: "heal", tier: 2 },
  { id: "grid-waffle", name: "Grid Waffle", emoji: "🧇", blurb: "Crispy grid that holds a lake of syrup. Deeply satisfying.", effect: "heal", tier: 2 },
  { id: "aged-crypt-cheese", name: "Aged Crypt Cheese", emoji: "🧀", blurb: "Sharp aged wheel with glowing veins. Potent, punchy strength.", effect: "power", tier: 2 },
  { id: "roast-leg", name: "Roast Leg", emoji: "🍖", blurb: "Giant roasted leg, caveman style. Raw primal power.", effect: "power", tier: 2 },
  { id: "drumstick", name: "Dungeon Drumstick", emoji: "🍗", blurb: "Juicy poultry leg from the roost pens. Classic fighter fuel.", effect: "power", tier: 2 },
  { id: "slab-steak", name: "Slab Steak", emoji: "🥩", blurb: "Thick-cut crypt-beast steak, seared rare. The apex power food.", effect: "power", tier: 3 },
  { id: "crisp-bacon", name: "Crisp Bacon", emoji: "🥓", blurb: "Strips of perfect crunch. A small salty surge of strength.", effect: "power", tier: 1 },
  { id: "warchief-burger", name: "Warchief Burger", emoji: "🍔", blurb: "A burger worthy of Groknak himself. A full war-feast in hand.", effect: "feast", tier: 2 },
  { id: "ember-fries", name: "Ember Fries", emoji: "🍟", blurb: "Golden fries, salted over embers. Snappy speed food.", effect: "haste", tier: 1 },
  { id: "whole-pizza", name: "Whole Pizza", emoji: "🍕", blurb: "An entire bubbling pie. Share with the party — or don't.", effect: "feast", tier: 2 },
  { id: "alley-hotdog", name: "Alley Hot Dog", emoji: "🌭", blurb: "Mystery meat, honest mustard. Street strength.", effect: "power", tier: 1 },
  { id: "packed-sandwich", name: "Packed Sandwich", emoji: "🥪", blurb: "Neat triangles packed for long delves. Tidy, tasty healing.", effect: "heal", tier: 2 },
  { id: "caravan-taco", name: "Caravan Taco", emoji: "🌮", blurb: "Spiced caravan filling in a crunchy shell. Portable fire.", effect: "power", tier: 2 },
  { id: "trail-burrito", name: "Trail Burrito", emoji: "🌯", blurb: "Everything the trail kitchen had, wrapped tight. A full meal.", effect: "feast", tier: 2 },
  { id: "steamed-tamale", name: "Steamed Tamale", emoji: "🫔", blurb: "Corn-husk parcel of slow-steamed comfort. Unwrap and recover.", effect: "feast", tier: 1 },
  { id: "garden-pita", name: "Garden Pita", emoji: "🥙", blurb: "Fresh pocket stuffed with garden greens. Light and mending.", effect: "heal", tier: 2 },
  { id: "falafel-plate", name: "Falafel Plate", emoji: "🧆", blurb: "Crisp golden balls with cool sauce. Humble, hearty strength.", effect: "power", tier: 1 },
  { id: "nest-egg", name: "Nest Egg", emoji: "🥚", blurb: "A speckled egg from the roost pens. Simple protein.", effect: "heal", tier: 1 },
  { id: "skillet-eggs", name: "Skillet Eggs", emoji: "🍳", blurb: "Sunny-side eggs still sizzling. Morning strength.", effect: "power", tier: 1 },
  { id: "crew-pan", name: "Crew Pan Stew", emoji: "🥘", blurb: "The whole crew's rations in one legendary pan. Feeds an army.", effect: "feast", tier: 3 },
  { id: "hearth-pot", name: "Hearth Pot", emoji: "🍲", blurb: "Bubbling pot that never empties on cold nights. Deep comfort.", effect: "feast", tier: 2 },
  { id: "melt-fondue", name: "Melt Fondue", emoji: "🫕", blurb: "A pot of molten cheese for dipping. Warm and warding.", effect: "feast", tier: 2 },
  { id: "trail-bowl", name: "Trail Bowl", emoji: "🥣", blurb: "Whatever fits in the bowl, eaten with a wooden spoon. Cozy.", effect: "heal", tier: 2 },
  { id: "scout-salad", name: "Scout Salad", emoji: "🥗", blurb: "Crisp greens that clear the mind. Eat light, notice everything.", effect: "focus", tier: 2 },
  { id: "watch-popcorn", name: "Watch Popcorn", emoji: "🍿", blurb: "Popped over the watch fire. Light snack, sharper senses.", effect: "focus", tier: 1 },
  { id: "churned-butter", name: "Churned Butter", emoji: "🧈", blurb: "Golden churned block. Coats you in a slick, rich ward.", effect: "shield", tier: 1 },
  { id: "pinch-salt", name: "Pinch of Salt", emoji: "🧂", blurb: "A sacred pinch. Ancient warding spice that clears the head.", effect: "focus", tier: 1 },
  { id: "pantry-can", name: "Pantry Can", emoji: "🥫", blurb: "Mystery preserves from the deep pantry. Surprisingly good.", effect: "heal", tier: 1 },
  { id: "voyager-bento", name: "Voyager Bento", emoji: "🍱", blurb: "Neat boxed feast with a bit of everything. A full voyage meal.", effect: "feast", tier: 2 },
  { id: "tide-cracker", name: "Tide Cracker", emoji: "🍘", blurb: "Salty rice cracker from the tide markets. Crunchy ward.", effect: "shield", tier: 1 },
  { id: "spirit-riceball", name: "Spirit Rice Ball", emoji: "🍙", blurb: "Triangle of rice with a surprise center. Comforting.", effect: "heal", tier: 2 },
  { id: "paddy-rice", name: "Paddy Rice", emoji: "🍚", blurb: "Steaming bowl of plain rice. The quiet base of every meal.", effect: "heal", tier: 1 },
  { id: "ember-curry", name: "Ember Curry", emoji: "🍛", blurb: "Curry that glows like coals. Fire you can eat.", effect: "power", tier: 2 },
  { id: "steam-noodles", name: "Steam Noodles", emoji: "🍜", blurb: "Slippery noodles in fragrant broth. Slurp and sprint.", effect: "haste", tier: 2 },
  { id: "cellar-spaghetti", name: "Cellar Spaghetti", emoji: "🍝", blurb: "Twirls of pasta in hearty sauce. Carbs for the campaign.", effect: "power", tier: 1 },
  { id: "ash-potato", name: "Ash-Roasted Sweet Potato", emoji: "🍠", blurb: "Caramelized sweet potato from the ash pits. Slow, sweet healing.", effect: "heal", tier: 2 },
  { id: "skewer-sticks", name: "Skewer Sticks", emoji: "🍢", blurb: "Grilled bites on a stick, eaten on the march. Quick fuel.", effect: "haste", tier: 1 },
  { id: "ronin-sushi", name: "Ronin Sushi", emoji: "🍣", blurb: "Precise cuts by a masterless chef. Elegant, deadly strength.", effect: "power", tier: 2 },
  { id: "golden-shrimp", name: "Golden Fried Shrimp", emoji: "🍤", blurb: "Crispy shrimp that snaps when you bite. Quick as the tide.", effect: "haste", tier: 1 },
  { id: "vortex-cake", name: "Vortex Fish Cake", emoji: "🍥", blurb: "Swirled cake with a hypnotic spiral. Stare, breathe, focus.", effect: "focus", tier: 1 },
  { id: "moon-cake", name: "Moon Cake", emoji: "🥮", blurb: "Dense festive cake stamped with the moon. Contemplative.", effect: "focus", tier: 2 },
  { id: "festival-skewers", name: "Festival Skewers", emoji: "🍡", blurb: "Sweet dumpling skewers from the night market. Festival speed.", effect: "haste", tier: 1 },
  { id: "pocket-dumpling", name: "Pocket Dumpling", emoji: "🥟", blurb: "Pleated pockets of savory filling. Small, warm, mending.", effect: "heal", tier: 1 },
  { id: "fortune-cookie", name: "Fortune Cookie", emoji: "🥠", blurb: "Cracks open with a prophecy inside. Luck favors the eater.", effect: "focus", tier: 1 },
  { id: "traveler-takeout", name: "Traveler Takeout Box", emoji: "🥡", blurb: "Folded box of roadside noodles and luck. Dinner anywhere.", effect: "feast", tier: 1 },
  { id: "king-crab", name: "King Crab", emoji: "🦀", blurb: "Claws like shields. Crack it for armor-grade meat.", effect: "shield", tier: 2 },
  { id: "abyss-lobster", name: "Abyss Lobster", emoji: "🦞", blurb: "Deep-trench lobster with crushing claws. Feast like the abyss.", effect: "power", tier: 2 },
  { id: "dart-shrimp", name: "Dart Shrimp", emoji: "🦐", blurb: "Tiny shrimp that flicks like an arrow. Eat and dart.", effect: "haste", tier: 2 },
  { id: "ink-squid", name: "Ink Squid", emoji: "🦑", blurb: "Slippery and quick, gone before you blink. Borrow its speed.", effect: "haste", tier: 1 },
  { id: "pearl-oyster", name: "Pearl Oyster", emoji: "🦪", blurb: "A shell hiding a pearl and a briny ward. Treasures protect.", effect: "shield", tier: 1 },
  { id: "crypt-icecream", name: "Crypt Ice Cream", emoji: "🍦", blurb: "Soft-serve swirled from cave-milk. Cold, sweet relief.", effect: "heal", tier: 2 },
  { id: "shave-ice", name: "Shave Ice", emoji: "🍧", blurb: "Mountain of flavored ice. Brain-freeze into overdrive.", effect: "haste", tier: 1 },
  { id: "triple-scoop", name: "Triple Scoop", emoji: "🍨", blurb: "Three scoops of pure morale. Dessert as medicine.", effect: "heal", tier: 2 },
  { id: "ring-donut", name: "Ring Donut", emoji: "🍩", blurb: "Glazed ring of joy. Sugar-powered concentration.", effect: "focus", tier: 1 },
  { id: "scout-cookie", name: "Scout Cookie", emoji: "🍪", blurb: "Crate of crumbly cookies sold at the gate. Sweet focus.", effect: "focus", tier: 1 },
  { id: "victory-cake", name: "Victory Cake", emoji: "🎂", blurb: "Candle-lit cake for cleared floors. The ultimate celebration feast.", effect: "feast", tier: 3 },
  { id: "slice-cake", name: "Slice of Cake", emoji: "🍰", blurb: "One perfect strawberry slice. A small, happy feast.", effect: "feast", tier: 2 },
  { id: "swirl-cupcake", name: "Swirl Cupcake", emoji: "🧁", blurb: "Frosted swirl in a paper cup. Pocket-sized happiness.", effect: "heal", tier: 1 },
  { id: "harvest-pie", name: "Harvest Pie", emoji: "🥧", blurb: "Lattice-top pie cooling on the sill. Autumn in a dish.", effect: "feast", tier: 1 },
  { id: "scholar-chocolate", name: "Scholar Chocolate", emoji: "🍫", blurb: "Dark squares for long study nights. Think deeper.", effect: "focus", tier: 2 },
  { id: "pocket-candy", name: "Pocket Candy", emoji: "🍬", blurb: "Shiny wrapped sweets. A quick sugary sprint.", effect: "haste", tier: 1 },
  { id: "spiral-lollipop", name: "Spiral Lollipop", emoji: "🍭", blurb: "Hypnotic swirl on a stick. Stare, focus, conquer.", effect: "focus", tier: 1 },
  { id: "caramel-pudding", name: "Caramel Pudding", emoji: "🍮", blurb: "Wobbling custard under amber caramel. Gentle and soothing.", effect: "heal", tier: 1 },
  { id: "golden-honey", name: "Golden Honey Pot", emoji: "🍯", blurb: "Thick honey from the hive vaults. Liquid gold healing.", effect: "heal", tier: 2 },
  { id: "whelp-bottle", name: "Whelp Bottle", emoji: "🍼", blurb: "Warm milk for the youngest delvers. Pure gentle care.", effect: "heal", tier: 2 },
  { id: "cave-milk", name: "Cave Milk", emoji: "🥛", blurb: "Fresh glass of cold cave-milk. Simple, strong bones.", effect: "heal", tier: 1 },
  { id: "watch-coffee", name: "Watch Coffee", emoji: "☕", blurb: "Black brew for the night watch. Eyes open, feet moving.", effect: "haste", tier: 2 },
  { id: "seer-teapot", name: "Seer Teapot", emoji: "🫖", blurb: "Leaves that swirl into fortunes. Drink and see further.", effect: "focus", tier: 2 },
  { id: "garden-tea", name: "Garden Tea", emoji: "🍵", blurb: "Grassy green cup, whisked to foam. Calm, clear focus.", effect: "focus", tier: 1 },
  { id: "rice-tonic", name: "Rice Tonic", emoji: "🍶", blurb: "Warm rice tonic in a small cup. Smooth steady clarity.", effect: "focus", tier: 1 },
  { id: "victory-cider", name: "Victory Sparkling Cider", emoji: "🍾", blurb: "Cork-popping sparkling cider for cleared bosses. A fizzy feast.", effect: "feast", tier: 2 },
  { id: "ember-juice", name: "Ember Juice", emoji: "🍷", blurb: "Dark berry juice in a fine glass. Sip and scheme.", effect: "focus", tier: 2 },
  { id: "frost-tonic", name: "Frost Tonic", emoji: "🍸", blurb: "Ice-cold citrus tonic with a twist. Chillingly quick.", effect: "haste", tier: 2 },
  { id: "tide-punch", name: "Tide Punch", emoji: "🍹", blurb: "Fruity island punch with a tiny umbrella. Vacation healing.", effect: "heal", tier: 2 },
  { id: "barley-brew", name: "Barley Brew", emoji: "🍺", blurb: "Foamy mug from the dwarf brewery. Hearty, brawny strength.", effect: "power", tier: 1 },
  { id: "oath-mugs", name: "Oath Mugs", emoji: "🍻", blurb: "Two mugs clanked in oath. Sworn strength for the whole party.", effect: "power", tier: 2 },
  { id: "toast-flutes", name: "Toast Flutes", emoji: "🥂", blurb: "Sparkling toast to fallen friends. Remember, focus, fight on.", effect: "focus", tier: 1 },
  { id: "smoked-tonic", name: "Smoked Oak Tonic", emoji: "🥃", blurb: "Smoky tonic over a single ice cube. Old, bold power.", effect: "power", tier: 2 },
  { id: "trail-soda", name: "Trail Soda", emoji: "🥤", blurb: "Fizzy cup with a bendy straw. Bubbles that hurry you along.", effect: "haste", tier: 1 },
  { id: "pearl-tea", name: "Pearl Milk Tea", emoji: "🧋", blurb: "Chewy pearls in creamy tea. Sip, chew, recover.", effect: "heal", tier: 1 },
  { id: "ration-juice", name: "Ration Juice Box", emoji: "🧃", blurb: "Boxed juice with a tiny straw. Field-ration refreshment.", effect: "heal", tier: 1 },
  { id: "mate-gourd", name: "Mate Gourd", emoji: "🧉", blurb: "Shared gourd passed around the fire. One sip each, all restored.", effect: "feast", tier: 1 },
];

export const GRAVEGAIN_FOOD_IDS: readonly string[] = GRAVEGAIN_FOOD_ROSTER.map(
  (r) => r.id,
);

export const GRAVEGAIN_FOOD_COUNT = GRAVEGAIN_FOOD_ROSTER.length;
