import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { rateLimit } from "@/lib/rate-limit";

export const dynamic = "force-dynamic";
const maxRequestBytes = 8192;
function error(message: string, status: number) { return NextResponse.json({ error: message }, { status, headers: { "Cache-Control": "private, no-store" } }); }
async function auth() { const supabase = await createClient(); const { data } = await supabase.auth.getUser(); return data.user ? { supabase, user: data.user } : null; }
export async function GET() { if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) return error("Supabase is not configured.", 503); const ctx = await auth(); if (!ctx) return error("Authentication required.", 401); const { data, error: dbError } = await ctx.supabase.from("profiles").select("display_name,email,created_at").eq("id", ctx.user.id).maybeSingle(); if (dbError) return error("Unable to load profile.", 500); return NextResponse.json({ profile: data }, { headers: { "Cache-Control": "private, no-store" } }); }
export async function PATCH(request: NextRequest) { if (Number(request.headers.get("content-length") ?? 0) > maxRequestBytes) return error("Profile request is too large.", 413); if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) return error("Supabase is not configured.", 503); const ctx = await auth(); if (!ctx) return error("Authentication required.", 401); const throttle = rateLimit(`profile-patch:${ctx.user.id}`, 20); if (!throttle.allowed) return NextResponse.json({ error: "Too many profile updates. Try again shortly." }, { status: 429, headers: { "Retry-After": String(throttle.retryAfter), "Cache-Control": "private, no-store" } }); let body: unknown; try { body = await request.json(); } catch { return error("Invalid JSON body.", 400); } const rawName = typeof body === "object" && body !== null ? (body as Record<string, unknown>).display_name : undefined; const name = typeof rawName === "string" ? rawName.trim() : ""; if (name.length < 2 || name.length > 40) return error("Display name needs 2-40 characters.", 400); const { error: dbError } = await ctx.supabase.from("profiles").update({ display_name: name }).eq("id", ctx.user.id); if (dbError) return error("Unable to save profile.", 500); return NextResponse.json({ success: true }, { headers: { "Cache-Control": "private, no-store" } }); }
