"use client";
import { useEffect, useState } from "react";

type Props = { orgId?: string; title?: string };
export function BudgetControls({ orgId, title = "Monthly budget" }: Props) {
  const [cap, setCap] = useState("0"), [alert, setAlert] = useState("80"), [hardStop, setHardStop] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { const url = `/api/budgets${orgId ? `?orgId=${orgId}` : ""}`; fetch(url).then(r => r.json()).then(({ budget }) => { if (budget) { setCap(String(budget.monthly_cap_coins)); setAlert(String(budget.alert_at_pct)); setHardStop(Boolean(budget.hard_stop)); } }).catch(() => setMessage("Unable to load budget.")); }, [orgId]);
  const save = async () => { setMessage("Saving…"); const res = await fetch("/api/budgets", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orgId, monthlyCapCoins: Number(cap), alertAtPct: Number(alert), hardStop }) }); const body = await res.json().catch(() => ({})); setMessage(res.ok ? "Budget saved." : String(body.error ?? "Unable to save budget.")); };
  return <section className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-slate-300">Set a monthly coin ceiling, early warning, and optional stop. A cap of 0 means monitoring without a limit.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm" htmlFor="budget-monthly-cap">Monthly cap (coins)<input id="budget-monthly-cap" name="monthlyCap" value={cap} type="number" min="0" step="0.01" onChange={e=>setCap(e.target.value)} className="mt-1 w-full rounded-lg border border-white/15 bg-black/30 px-3 py-2" /></label><label className="text-sm" htmlFor="budget-alert-pct">Alert at (%)<input id="budget-alert-pct" name="alertPct" value={alert} type="number" min="1" max="100" onChange={e=>setAlert(e.target.value)} className="mt-1 w-full rounded-lg border border-white/15 bg-black/30 px-3 py-2" /></label><label className="flex items-end gap-2 pb-2 text-sm"><input id="budget-hard-stop" name="hardStop" checked={hardStop} type="checkbox" onChange={e=>setHardStop(e.target.checked)} /> Stop new spend at cap</label></div><button onClick={save} className="mt-4 rounded-lg bg-cyan-300 px-4 py-2 font-semibold text-slate-950">Save budget</button><p role="status" className="mt-2 text-sm text-slate-400">{message}</p></section>;
}
