"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { checkDob, DEFAULT_DOB_ISO } from "@/lib/age-gate";
import { GRAVEGAIN_MISSIONS } from "@/content/gravegain/missions";

type Audience = "kids" | "teens" | "adults";
type Progress = Record<string, number>;
const LOCAL_KEY = "gravegain-universe-progress-v1";
function readLocal(): Progress { try { return JSON.parse(localStorage.getItem(LOCAL_KEY) || "{}"); } catch { return {}; } }
function addLocal(key: string): number { const p = readLocal(); p[key] = (p[key] || 0) + 1; localStorage.setItem(LOCAL_KEY, JSON.stringify(p)); return p[key]; }
function ageFromDob(value: string): Audience | null { if (checkDob(value, 18).ok) return "adults"; if (checkDob(value, 13).ok) return "teens"; const kids = checkDob(value, 0); return kids.ok ? "kids" : null; }
function useProgress() {
  const [counts, setCounts] = useState<Progress>(() => typeof window === "undefined" ? {} : readLocal());
  const [signedIn, setSignedIn] = useState(false);
  useEffect(() => { fetch("/api/gravegain/progress").then(r => r.json()).then(d => { setSignedIn(Boolean(d.signedIn)); const next: Progress = { ...readLocal() }; for (const row of d.rows || []) next[`${row.kind}:${row.item_id}`] = Math.max(Number(next[`${row.kind}:${row.item_id}`]) || 0, Number(row.count) || 0); setCounts(next); }).catch(() => {}); }, []);
  async function collect(kind: "lore" | "mission", id: string) { const key = `${kind}:${id}`; const local = addLocal(key); setCounts(p => ({ ...p, [key]: local })); try { const r = await fetch("/api/gravegain/progress", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, item_id: id }) }); const d = await r.json(); if (r.ok && Number.isFinite(Number(d.count))) { setCounts(p => ({ ...p, [key]: Number(d.count) })); setSignedIn(true); } } catch { /* guest device progress remains available */ } }
  return { counts, signedIn, collect };
}
function useAgeGate() {
  const [dob, setDob] = useState(DEFAULT_DOB_ISO); const [age, setAge] = useState<Audience | null>(null); const [error, setError] = useState("");
  function submit() { const result = ageFromDob(dob); if (!result) { setError("Enter a valid date of birth."); return; } setAge(result); setError(""); }
  return { age, dob, setDob, error, submit, select: setAge };
}
function PageShell({ children, title }: { children: React.ReactNode; title: string }) { return <main className="min-h-screen bg-slate-950 px-4 py-12 text-white"><div className="mx-auto max-w-5xl"><Link href="/games" className="text-cyan-300 hover:underline">← Games</Link><p className="mt-8 text-sm font-bold uppercase tracking-[.3em] text-violet-300">The GraveGain shared universe</p><h1 className="mt-2 text-4xl font-black sm:text-5xl">{title}</h1>{children}</div></main>; }
function AgeForm({ dob, setDob, error, submit }: { dob: string; setDob: (v:string)=>void; error:string; submit:()=>void }) { return <section className="mt-6 rounded-2xl border border-amber-300/30 bg-amber-300/5 p-5"><h2 className="font-bold">Choose your reading age</h2><p className="mt-1 text-sm text-slate-300">Your date is checked in this browser and is not saved or sent.</p><div className="mt-3 flex flex-wrap items-end gap-3"><label className="grid gap-1 text-sm">Date of birth<input type="date" value={dob} onChange={e=>setDob(e.target.value)} className="rounded-lg border border-white/20 bg-slate-900 px-3 py-2 text-white" /></label><button onClick={submit} className="rounded-lg bg-amber-300 px-4 py-2 font-bold text-slate-950">Continue</button></div>{error&&<p role="alert" className="mt-2 text-sm text-red-300">{error}</p>}</section>; }
function useCounts() { return useProgress(); }
export function GraveGainHome() { const p=useCounts(); return <PageShell title="One universe. Every dimension."><p className="mt-5 max-w-3xl text-lg text-slate-300">Every GraveGain game takes place in the same shared universe. Each dimension explores another slice of MoonRock, its people, and the growing necrogenesis. The alphabet is open: every dimension can have A, B, C, and more as new games arrive.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><Link className="rounded-2xl border border-violet-300/20 bg-violet-300/5 p-5 hover:border-violet-300/60" href="/gravegain/lore"><b>📚 Shared Lore</b><p className="mt-2 text-sm text-slate-300">Read lore from across every game and track what you have collected.</p></Link><Link className="rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-5 hover:border-cyan-300/60" href="/gravegain/missions"><b>🧭 Mission Atlas</b><p className="mt-2 text-sm text-slate-300">See every mission and your cross-version completion record.</p></Link><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><b>🔓 Your discoveries</b><p className="mt-2 text-sm text-slate-300">{Object.values(p.counts).filter(Boolean).length} tracked lore and mission records on this device{p.signedIn?" · account sync active":" · sign in to sync across devices"}.</p></div></div><h2 className="mt-10 text-2xl font-black">The dimension line</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["1dA","2dA","2dB","3dA","4dA","5dA"].map(x=><div key={x} className="rounded-xl border border-white/10 bg-white/[.03] p-4"><span className="font-black text-cyan-200">GraveGain{x}</span><p className="mt-1 text-sm text-slate-400">{x==="1dA"?"The Ley-Line March":"A connected chapter in the MoonRock universe"}</p><Link className="mt-2 inline-block text-sm text-cyan-300 hover:underline" href={`/games/gravegain${x}`}>Game page →</Link></div>)}</div></PageShell>; }
export function GraveGainLorePage() { const gate=useAgeGate(); const p=useCounts(); const [filter,setFilter]=useState<Audience>("adults"); const [lore,setLore]=useState<Array<{id:string;title:string;category:string;type:string;rarity:string;content:string;audience:Audience;game:string}>>([]); useEffect(()=>{fetch("/api/gravegain/lore").then(r=>r.json()).then(d=>setLore(d.lore||[])).catch(()=>{});},[]); const allowed=gate.age ?? null; const visible=useMemo(()=>lore.filter(x=>allowed==="adults"?true:allowed==="teens"?x.audience!=="adults":allowed==="kids"?x.audience==="kids":false),[allowed,lore]); const unlocked=new Set(Object.keys(p.counts).filter(k=>k.startsWith("lore:")).map(k=>k.slice(5))); return <PageShell title="The Lore Library"><p className="mt-4 text-slate-300">Read the shared-world archives without an account. When you find a lore record in a game, its first collection and later discoveries count across the whole universe.</p>{!gate.age&&<AgeForm {...gate}/>}<div className="mt-5 flex flex-wrap gap-2">{(["adults","teens","kids"] as Audience[]).map(a=><button key={a} onClick={()=>allowed?setFilter(a):undefined} disabled={!allowed|| (allowed==="teens"&&a==="adults") || (allowed==="kids"&&a!=="kids")} className={`rounded-full border px-4 py-2 text-sm font-bold ${filter===a?"border-violet-300 bg-violet-300/15 text-violet-100":"border-white/15 text-slate-300"} disabled:opacity-40`}>{a[0].toUpperCase()+a.slice(1)} lore</button>)}</div>{allowed&&<p className="mt-3 text-xs text-slate-400">Showing {filter} lore available to your age selection.</p>}<div className="mt-6 grid gap-4">{visible.filter(x=>filter==="adults"?true:filter==="teens"?x.audience!=="adults":x.audience==="kids").map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-violet-300">{x.category} · {x.type} · {x.game}</p><h2 className="mt-1 text-xl font-bold">{x.title}</h2></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{x.audience} · {p.counts[`lore:${x.id}`]||0} collections</span></div><pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-relaxed text-slate-300">{x.content}</pre><button onClick={()=>void p.collect("lore",x.id)} className="mt-4 rounded-lg border border-cyan-300/40 px-3 py-2 text-sm font-bold text-cyan-200 hover:bg-cyan-300/10">{unlocked.has(x.id)?"Collected before · collect again":"Mark as collected"}</button></article>)}</div></PageShell>; }
export function GraveGainMissionsPage() { const p=useCounts(); const [done,setDone]=useState<Set<string>>(new Set()); return <PageShell title="Mission Atlas"><p className="mt-4 text-slate-300">Full GraveGain completion means completing every mission in every version. This atlas brings the mission list together; progress follows your account when you sign in, or stays on this device as a guest.</p><p className="mt-3 font-bold text-cyan-200">{done.size} / {GRAVEGAIN_MISSIONS.length} missions marked complete · full completion requires all versions.</p><div className="mt-6 grid gap-4">{GRAVEGAIN_MISSIONS.map(m=>{const complete=done.has(m.id)||Boolean(p.counts[`mission:${m.id}`]);return <article key={m.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-cyan-300">{m.game}</p><h2 className="mt-1 text-xl font-bold">{m.title}</h2></div><span className="text-sm">{complete?"✅ Complete":"⬜ Not recorded"}</span></div><p className="mt-3 text-sm text-slate-300">{m.detail}</p><button onClick={()=>{setDone(s=>new Set(s).add(m.id));void p.collect("mission",m.id);}} className="mt-4 rounded-lg border border-cyan-300/40 px-3 py-2 text-sm font-bold text-cyan-200 hover:bg-cyan-300/10">{complete?"Record another completion":"Mark complete"}</button><Link className="ml-3 text-sm text-cyan-300 hover:underline" href={`/games/${m.game.replace("GraveGain", "gravegain")}`}>Open game →</Link></article>;})}</div></PageShell>; }
